### ISSUE TITLE
bundle rake  failed 

### ISSUE THREAD

**Issue by N00D13** [locomotivecms/engine#1044]
after bundle install i got 
```
bundle exec rake
rake aborted!
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
/var/lib/gems/2.1.0/gems/execjs-2.5.2/lib/execjs/runtimes.rb:48:in `autodetect'
/var/lib/gems/2.1.0/gems/execjs-2.5.2/lib/execjs.rb:5:in `<module:ExecJS>'
/var/lib/gems/2.1.0/gems/execjs-2.5.2/lib/execjs.rb:4:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.1.0/gems/autoprefixer-rails-5.1.11/lib/autoprefixer-rails/processor.rb:2:in `<top (required)>'
/var/lib/gems/2.1.0/gems/autoprefixer-rails-5.1.11/lib/autoprefixer-rails.rb:29:in `require_relative'
/var/lib/gems/2.1.0/gems/autoprefixer-rails-5.1.11/lib/autoprefixer-rails.rb:29:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/home/alex/engine/lib/locomotive/dependencies.rb:15:in `<top (required)>'
/home/alex/engine/lib/locomotive/engine.rb:1:in `require'
/home/alex/engine/lib/locomotive/engine.rb:1:in `<top (required)>'
/home/alex/engine/lib/locomotive_cms.rb:1:in `require'
/home/alex/engine/lib/locomotive_cms.rb:1:in `<top (required)>'
/var/lib/gems/2.1.0/gems/bundler-1.10.0.pre.2/lib/bundler/runtime.rb:76:in `require'
/var/lib/gems/2.1.0/gems/bundler-1.10.0.pre.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/var/lib/gems/2.1.0/gems/bundler-1.10.0.pre.2/lib/bundler/runtime.rb:72:in `each'
/var/lib/gems/2.1.0/gems/bundler-1.10.0.pre.2/lib/bundler/runtime.rb:72:in `block in require'
/var/lib/gems/2.1.0/gems/bundler-1.10.0.pre.2/lib/bundler/runtime.rb:61:in `each'
/var/lib/gems/2.1.0/gems/bundler-1.10.0.pre.2/lib/bundler/runtime.rb:61:in `require'
/var/lib/gems/2.1.0/gems/bundler-1.10.0.pre.2/lib/bundler.rb:128:in `require'
/home/alex/engine/spec/dummy/config/application.rb:11:in `<top (required)>'
/home/alex/engine/spec/dummy/Rakefile:4:in `require'
/home/alex/engine/spec/dummy/Rakefile:4:in `<top (required)>'
/home/alex/engine/Rakefile:9:in `load'
/home/alex/engine/Rakefile:9:in `<top (required)>'
(See full trace by running task with --trace)
alex@LocomotiveTest:~/engine$ 
```

**Comment by N00D13** [comment]
Sorry my fault, NodeJS was not installed
