### ISSUE TITLE
Locomotive install - cannot load such file -- sanitize

### ISSUE THREAD

**Issue by gabskoro** [locomotivecms/engine#1046]
Hi,

I'm pulling the gem from github 

    gem 'locomotivecms', git: 'git@github.com:locomotivecms/engine.git'

And after I run

    bundle exec rails g locomotive:install

I'm getting this error
````ruby
/Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- sanitize (LoadError)
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/engine-bdb21197bfc9/lib/locomotive/dependencies.rb:27:in `<top (required)>'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/engine-bdb21197bfc9/lib/locomotive/engine.rb:1:in `require'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/engine-bdb21197bfc9/lib/locomotive/engine.rb:1:in `<top (required)>'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/engine-bdb21197bfc9/lib/locomotivecms.rb:1:in `require'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/engine-bdb21197bfc9/lib/locomotivecms.rb:1:in `<top (required)>'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:76:in `require'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:72:in `each'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:61:in `each'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:61:in `require'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler.rb:134:in `require'
	from /Users/gabrijel/dev/hpb-web/acme_cms/config/application.rb:16:in `<top (required)>'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:141:in `require'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/gabrijel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
````
I'm getting the same error if I just run `rails s` and without this gem everything works fine.

**Comment by did** [comment]
it should be fixed in one of the previous commits.
