### ISSUE TITLE
cannot auth in API

### ISSUE THREAD

**Issue by kritik** [locomotivecms/engine#1049]
I have new installation of master version
I do connection by coal doc:
```
2.2.1 :001 > require 'locomotive/coal'
 => true 
2.2.1 :002 > client = Locomotive::Coal::Client.new('http://localhost:3000', { email: "xxx@xx.com", token: "f0ac703565dfe72efbb24c9003db558eeb3035b9"})
 => #<Locomotive::Coal::Client:0x007f8dc30f7a78 @options={"path_prefix"=>"locomotive"}, @uri=#<URI::HTTP http://localhost:3000/locomotive/api/v3>, @credentials={"email"=>"s6numid@gmail.com", "token"=>"f0ac703565dfe72efbb24c9003db558eeb3035b9"}> 
2.2.1 :003 > client.my_account.get
Locomotive::Coal::UnauthorizedError: 401 Unauthorized
	from /Users/vladimir/.rvm/gems/ruby-2.2.1@familyid-web/gems/locomotivecms_coal-1.0.0.pre.alpha.3/lib/locomotive/coal/resources/concerns/request.rb:36:in `do_request'
	from /Users/vladimir/.rvm/gems/ruby-2.2.1@familyid-web/gems/locomotivecms_coal-1.0.0.pre.alpha.3/lib/locomotive/coal/resources/concerns/request.rb:7:in `get'
	from /Users/vladimir/.rvm/gems/ruby-2.2.1@familyid-web/gems/locomotivecms_coal-1.0.0.pre.alpha.3/lib/locomotive/coal/resources/my_account.rb:9:in `get'
	from (irb):3
	from /Users/vladimir/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
```

But engine checks auth by authentication_token
https://github.com/locomotivecms/engine/blob/981b838031527cf19922a63045a68b360aff7985/app/api/locomotive/api/helpers/authentication_helper.rb#L12

```
Started GET "/locomotive/api/v3/my_account.json" for ::1 at 2015-07-20 10:21:51 +0300
  MOPED: 127.0.0.1:27017 COMMAND      database=admin command={:ismaster=>1} runtime: 0.4250ms
  MOPED: 127.0.0.1:27017 QUERY        database=familyid_web_dev collection=locomotive_accounts selector={"$query"=>{"email"=>"xxx@xx.com", "authentication_token"=>"f0ac703565dfe72efbb24c9003db558eeb3035b9"}, "$orderby"=>{:_id=>1}} flags=[] limit=-1 skip=0 batch_size=nil fields=nil runtime: 0.3180ms
service="api.request" method="GET" endpoint="/v3/my_account.json" params="{"auth_token"=>"f0ac703565dfe72efbb24c9003db558eeb3035b9"}" headers="{"HTTP_X_LOCOMOTIVE_ACCOUNT_EMAIL"=>"xxx@xx.com", "HTTP_X_LOCOMOTIVE_ACCOUNT_TOKEN"=>"f0ac703565dfe72efbb24c9003db558eeb3035b9"}" status="401" timestamp="2015-07-20 07:21:51 UTC"
```

My DB record:
```
 #<Locomotive::Account _id: 55a785e6766c61f801000000, created_at: 2015-07-16 10:22:30 UTC, updated_at: 2015-07-20 06:31:50 UTC, api_key: "f0ac703565dfe72efbb24c9003db558eeb3035b9", remember_created_at: nil, email: "xxxxx@xxx.com", encrypted_password: "xxxxx", authentication_token: "2o2vwzLXFCaHymTUfQXF", reset_password_token: nil, reset_password_sent_at: nil, password_salt: "xxxx", sign_in_count: 2, current_sign_in_at: 2015-07-20 06:31:50 UTC, last_sign_in_at: 2015-07-16 10:22:30 UTC, current_sign_in_ip: "::1", last_sign_in_ip: "::1", avatar: nil, name: "Vladimir", locale: "en", super_admin: false>
```

Should I do pull request to fix it?

**Comment by kritik** [comment]
Strange, I thought I close it as newest versions of engine and wagon are working wit each other.

**Comment by boie0025** [comment]
@kritik Try use api_key instead:
client = Locomotive::Coal::Client.new('http://localhost:3000', { email: "xxx@xx.com", api_key: "f0ac703565dfe72efbb24c9003db558eeb3035b9"})
