### ISSUE TITLE
cannot push from wagon

### ISSUE THREAD

**Issue by catalanska** [locomotivecms/engine#1054]
Hello, I am new to locomotivecms, trying to test it for a new project. I could setup everything but can't push my changes from wagon to the engine. 
My current stack is:
ruby 2.2.2, rails 4.2.3, locomotivecms_wagon, 1.5.7, locomotivecms, 3.0.0.pre.alpha.2

Working under development mode, everything ok until I try 'wagon push development' to my local engine. The backtrace in the engine side is: 

```
Started POST "/locomotive/api/tokens.json" for 127.0.0.1 at 2015-07-31 18:47:48 +0200

NoMethodError (undefined method `params' for nil:NilClass):
  /home/javierjv/.rvm/gems/ruby-2.2.2/bundler/gems/engine-e9578cfeae9c/app/api/locomotive/api/middlewares/logger_middleware.rb:28:in `payload'
  /home/javierjv/.rvm/gems/ruby-2.2.2/bundler/gems/engine-e9578cfeae9c/app/api/locomotive/api/middlewares/logger_middleware.rb:22:in `log_message'
  /home/javierjv/.rvm/gems/ruby-2.2.2/bundler/gems/engine-e9578cfeae9c/app/api/locomotive/api/middlewares/logger_middleware.rb:13:in `block in call'
  /home/javierjv/.rvm/gems/ruby-2.2.2/bundler/gems/engine-e9578cfeae9c/app/api/locomotive/api/middlewares/logger_middleware.rb:12:in `tap'
  /home/javierjv/.rvm/gems/ruby-2.2.2/bundler/gems/engine-e9578cfeae9c/app/api/locomotive/api/middlewares/logger_middleware.rb:12:in `call'
  /home/javierjv/.rvm/gems/ruby-2.2.2/bundler/gems/engine-e9578cfeae9c/app/api/locomotive/api/middlewares/locale_middleware.rb:21:in `block in call'
  custom_fields (2.4.0.rc3) lib/custom_fields/extensions/mongoid/fields/i18n.rb:46:in `with_locale'
  /home/javierjv/.rvm/gems/ruby-2.2.2/bundler/gems/engine-e9578cfeae9c/app/api/locomotive/api/middlewares/locale_middleware.rb:20:in `call'
  rack (1.6.4) lib/rack/builder.rb:153:in `call'
  actionpack (4.2.3) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
  /home/javierjv/.rvm/gems/ruby-2.2.2/bundler/gems/engine-e9578cfeae9c/lib/locomotive/middlewares/site.rb:11:in `call'
  dragonfly (1.0.10) lib/dragonfly/middleware.rb:14:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.3) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  /home/javierjv/.rvm/gems/ruby-2.2.2/bundler/gems/engine-e9578cfeae9c/lib/locomotive/middlewares/permalink.rb:17:in `call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  dragonfly (1.0.10) lib/dragonfly/cookie_monster.rb:9:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /home/javierjv/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /home/javierjv/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /home/javierjv/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

I hope it helps

**Comment by cappadona** [comment]
Also new to Locomotive and trying to work with v3 when I ran into this same issue in the `payload` method of `logger_middleware.rb` whenever pushing/pulling with Wagon.
```ruby
NoMethodError (undefined method `params' for nil:NilClass)
```
> The `nil` object referenced is [`env['api.endpoint']`](https://github.com/locomotivecms/engine/blob/7fa847cd2c19e1161a8639ea655fc8186e153ac7/app/api/locomotive/api/middlewares/logger_middleware.rb#L28).

By dumb luck, I was able to trace this back to a **compatibility issue with the Wagon version**. I had been using Wagon 1.5.7 just like you, and following the [Locomotive v3 alpha documentation](https://locomotive-v3.readme.io/docs/getting-started), it wasn't clear to me there is also an alpha release of Wagon available -- that note about upgrading Wagon via `bundle upgrade` in the [last section of the guide](https://locomotive-v3.readme.io/docs/getting-started#pushing-a-site-template-with-wagon) confused me because it really only applies to the `My Portfolio` example site whose Gemfile references a pre release of Wagon.

So, long story short, you need to use a pre release of Wagon with Locomotive v3. You'll find [several available on rubygems](https://rubygems.org/gems/locomotivecms_wagon) and you can ensure that you're using the latest by either:

* adding this to the Gemfile of your Wagon site in question
```ruby
gem 'locomotivecms_wagon', '>= 2.0.0.alpha'
```
* or installing Wagon directly via `gem install`
```ruby
gem install locomotivecms_wagon --pre
```
> Found this nugget in @did's [recent commit](https://github.com/locomotivecms/engine/commit/0739682#diff-172795c13038498dbc08b213ad7479b6) adding developer documentation

[Any 2.0.0 alpha release](https://github.com/locomotivecms/wagon/commit/05abc8060e9c096c5eef6f06bd8d64d4708a5595#diff-b9b0dfa6af1c6a45194c16a05dee384eR28) of Wagon will ensure you're also using [Coal](https://github.com/locomotivecms/coal), the Ruby API client introduced for Locomotive v3. This is important to note, since Coal is responsible for [defining the endpoint path of the API](https://github.com/locomotivecms/coal/blame/32b2844bf74fb05ed0a3bdf428c6308ea33fb5d0/lib/locomotive/coal/client.rb#L66). You'll see that `wagon push` now POSTs to `/locomotive/api/v3/tokens.json` and your error is no more.

Good luck.

**Comment by catalanska** [comment]
Perfect! you were totally right. I hadn't noticed about new version of Wagon and had assume that new engine was compatible with previous Wagon.

 Thanks a lot @cappadona !
