### ISSUE TITLE
Cannot use coal anymore

### ISSUE THREAD

**Issue by catalanska** [locomotivecms/engine#1060]
Hello, 

I've been testing latest changes on both coal and engine. I had created a script to fill up my database,  but now I am not able to do even simple queries.

As an example:

If I run 

```
client = Locomotive::Coal::Client.new(HOST { email:EMAIL, api_key: API_KEY })
site_client = client.scope_by('warm-tundra-4331')
site_client.contents.photos.all
```

I get this on server side

```
 MOPED: 127.0.0.1:27017 QUERY        database=engine_test_dev collection=locomotive_content_types selector={"$query"=>{"site_id"=>BSON::ObjectId('5612ba935583191545000001'), "$or"=>[{"_id"=>"photos"}, {"slug"=>"photos"}]}, "$orderby"=>{:_id=>1}} flags=[] limit=-1 skip=0 batch_size=nil fields=nil runtime: 1.5603ms

NoMethodError (undefined method `num_pages' for #<Mongoid::Criteria:0x007f97c854a558>):
  mongoid (4.0.2) lib/mongoid/criteria.rb:523:in `method_missing'
  locomotivecms (3.0.0.pre.beta.1) app/api/locomotive/api/helpers/pagination_helper.rb:7:in `add_pagination_header'
  locomotivecms (3.0.0.pre.beta.1) app/api/locomotive/api/resources/content_entry_resource.rb:34:in `block (2 levels) in <class:ContentEntryResource>'
  grape (0.12.0) lib/grape/endpoint.rb:47:in `call'
  grape (0.12.0) lib/grape/endpoint.rb:47:in `block in generate_api_method'
  grape (0.12.0) lib/grape/endpoint.rb:247:in `call'
  grape (0.12.0) lib/grape/endpoint.rb:247:in `run'
```

Best

**Comment by did** [comment]
@catalanska, good point. I've fixed it this week. Here is the commit: https://github.com/locomotivecms/engine/commit/aff744a35d9c0c3f5b6239d876958c91bdc2b71f

**Comment by catalanska** [comment]
great, thanks!
