### ISSUE TITLE
[v3] Page caching throws a 500

### ISSUE THREAD

**Issue by allanbreyes** [locomotivecms/engine#1075]
Once the cache is enabled, it seems my application is throwing 500's.  Here's the most recent stack trace:

```
App 10320 stdout:   MOPED: 54.234.96.145:10593 QUERcY        database=[production] collection=locomotive_snippets selector={"site_id"=>BSON::ObjectId('564182a43220830f0e00000d'), "slug"=>"footer"} flags=[] limit=0 skip=0 batch_size=nil fields=nil runtime: 70.4730ms
App 10320 stdout: 
App 10320 stdout: NoMethodError (undefined method `fullpath' for nil:NilClass):
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/liquid/tags/editable/base.rb:14:in `initialize'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/tag.rb:9:in `new'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/tag.rb:9:in `parse'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/block_body.rb:27:in `parse'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/document.rb:10:in `parse'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/document.rb:5:in `parse'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/template.rb:124:in `parse'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/template.rb:110:in `parse'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/tags/include.rb:75:in `load_cached_partial'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/tags/include.rb:46:in `render'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/liquid/tags/snippet.rb:20:in `render'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/block_body.rb:105:in `render_token'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/block_body.rb:87:in `block in render'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/block_body.rb:74:in `each'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/block_body.rb:74:in `render'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/block.rb:15:in `render'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/tags/inherited_block.rb:71:in `block in render'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/context.rb:128:in `stack'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/tags/inherited_block.rb:64:in `render'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/block_body.rb:105:in `render_token'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/block_body.rb:87:in `block in render'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/block_body.rb:74:in `each'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/block_body.rb:74:in `render'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/template.rb:215:in `block in render'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/template.rb:269:in `with_profiling'
App 10320 stdout:   locomotivecms-liquid (4.0.0.alpha2) lib/liquid/template.rb:214:in `render'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/renderer.rb:34:in `parse_and_render_liquid'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/renderer.rb:22:in `render_page'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/renderer.rb:10:in `_call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
App 10320 stdout:   /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/bundler/gems/engine-4a00ffbb69da/lib/locomotive/steam/middlewares/cache.rb:31:in `fetch_cached_response'
App 10320 stdout:   /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/bundler/gems/engine-4a00ffbb69da/lib/locomotive/steam/middlewares/cache.rb:17:in `call'
App 10320 stdout:   /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/bundler/gems/engine-4a00ffbb69da/lib/locomotive/steam/middlewares/page_editing.rb:14:in `call'
App 10320 stdout:   /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/bundler/gems/engine-4a00ffbb69da/lib/locomotive/steam/middlewares/missing_translations.rb:13:in `block in call'
App 10320 stdout:   /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/bundler/gems/engine-4a00ffbb69da/lib/locomotive/steam/middlewares/missing_translations.rb:24:in `find_and_persist_missing_translations'
App 10320 stdout:   /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/bundler/gems/engine-4a00ffbb69da/lib/locomotive/steam/middlewares/missing_translations.rb:12:in `call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/path.rb:13:in `call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/locale.rb:24:in `block in _call'
App 10320 stdout:   i18n (0.7.0) lib/i18n.rb:257:in `with_locale'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/locale.rb:23:in `_call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/timezone.rb:16:in `block in _call'
App 10320 stdout:   activesupport (4.2.4) lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/timezone.rb:15:in `_call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/robots.rb:15:in `call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/logging.rb:18:in `call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/default_env.rb:15:in `call'
App 10320 stdout:   dragonfly (1.0.12) lib/dragonfly/middleware.rb:14:in `call'
App 10320 stdout:   locomotivecms_steam (1.0.0.rc2) lib/locomotive/steam/middlewares/favicon.rb:15:in `call'
App 10320 stdout:   rack-rewrite (1.5.1) lib/rack/rewrite.rb:24:in `call'
App 10320 stdout:   rack (1.6.4) lib/rack/builder.rb:153:in `call'
App 10320 stdout:   actionpack (4.2.4) lib/action_dispatch/routing/mapper.rb:51:in `serve'
App 10320 stdout:   actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in `block in serve'
App 10320 stdout:   actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `each'
App 10320 stdout:   actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `serve'
App 10320 stdout:   actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
App 10320 stdout:   /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/bundler/gems/engine-4a00ffbb69da/lib/locomotive/middlewares/site.rb:24:in `call'
App 10320 stdout:   dragonfly (1.0.12) lib/dragonfly/middleware.rb:14:in `call'
App 10320 stdout:   warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
App 10320 stdout:   warden (1.2.3) lib/warden/manager.rb:34:in `catch'
App 10320 stdout:   warden (1.2.3) lib/warden/manager.rb:34:in `call'
App 10320 stdout:   rack (1.6.4) lib/rack/etag.rb:24:in `call'
App 10320 stdout:   rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
App 10320 stdout:   rack (1.6.4) lib/rack/head.rb:13:in `call'
App 10320 stdout:   actionpack (4.2.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
App 10320 stdout:   actionpack (4.2.4) lib/action_dispatch/middleware/flash.rb:260:in `call'
App 10320 stdout:   rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
App 10320 stdout:   rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
App 10320 stdout:   actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:560:in `call'
App 10320 stdout:   actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
App 10320 stdout:   activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
App 10320 stdout:   activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
App 10320 stdout:   activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
App 10320 stdout:   actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
App 10320 stdout:   actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
App 10320 stdout:   actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
App 10320 stdout:   actionpack (4.2.4) lib/action_dispatch/middlewar
App 10320 stdout: e/show_exceptions.rb:30:in `call'
App 10320 stdout:   railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
App 10320 stdout:   railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
App 10320 stdout:   activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
App 10320 stdout:   activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
App 10320 stdout:   activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
App 10320 stdout:   railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
App 10320 stdout:   actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
App 10320 stdout:   rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
App 10320 stdout:   rack (1.6.4) lib/rack/runtime.rb:18:in `call'
App 10320 stdout:   activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
App 10320 stdout:   dragonfly (1.0.12) lib/dragonfly/cookie_monster.rb:9:in `call'
App 10320 stdout:   rack-cache (1.5.1) lib/rack/cache/context.rb:140:in `forward'
App 10320 stdout:   rack-cache (1.5.1) lib/rack/cache/context.rb:249:in `fetch'
App 10320 stdout:   rack-cache (1.5.1) lib/rack/cache/context.rb:189:in `lookup'
App 10320 stdout:   rack-cache (1.5.1) lib/rack/cache/context.rb:66:in `call!'
App 10320 stdout:   rack-cache (1.5.1) lib/rack/cache/context.rb:51:in `call'
App 10320 stdout:   actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
App 10320 stdout:   rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
App 10320 stdout:   railties (4.2.4) lib/rails/engine.rb:518:in `call'
App 10320 stdout:   railties (4.2.4) lib/rails/application.rb:165:in `call'
```

**Comment by did** [comment]
It was caused by editable elements found inside a snippet. Editable elements should not be used inside a snippet.
