### ISSUE TITLE
Liquid error: PageNotFound in Locomotive::EditableElementsController#index

### ISSUE THREAD

**Issue by CedricLor** [locomotivecms/engine#1087]
With the latest version of the Engine (commit 9101694ad), I now get a recurrent error which prevents any use of the Engine, whether on Heroku or on my local Engine. Engine/Steam does not seem to properly extends parents from Liquid markup (I do have a layouts/simple.liquid file and it is correctly referenced in its children).

Please see below the backtrace.

Also, something strange is that I get the handle “purring-sunshine-3336” from the session dump:
"/locomotive/purring-sunshine-3336/content_types/photos/entries/5656779f3a7dbc016d00028d/edit"

while I get the handle “pleasant-snowflake-6695” in the url and the params for the site handle:
http://localhost:3000/locomotive/pleasant-snowflake-6695/pages/565a2c543a7dbc6f62000055/editable_elements

Please also see the related error reported in the Wagon ANO.
——————

    Liquid error: Extending a missing page. Page/Layout with fullpath 'layouts/simple' was not found

            # no need to go further if the parent does not exist
            raise PageNotFound.new("Extending a missing page. Page/Layout with fullpath '#{@template_name}' was not found") if parent.nil?

            ActiveSupport::Notifications.instrument('steam.parse.extends', page: options[:page], parent: parent)

    /Users/developer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-a5be3f87565a/lib/locomotive/steam/liquid/tags/extends.rb:20:in `parse_parent_template'
    locomotivecms-liquid (4.0.0) lib/liquid/tags/extends.rb:30:in `parse'
    locomotivecms-liquid (4.0.0) lib/liquid/tag.rb:10:in `parse'
    locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:27:in `parse'
    locomotivecms-liquid (4.0.0) lib/liquid/document.rb:10:in `parse'
    locomotivecms-liquid (4.0.0) lib/liquid/document.rb:5:in `parse'
    locomotivecms-liquid (4.0.0) lib/liquid/template.rb:124:in `parse'
    /Users/developer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-a5be3f87565a/lib/locomotive/steam/liquid/template.rb:24:in `parse'
    /Users/developer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-a5be3f87565a/lib/locomotive/steam/services/liquid_parser_service.rb:19:in `_parse'
    /Users/developer/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/steam-a5be3f87565a/lib/locomotive/steam/services/liquid_parser_service.rb:9:in `parse'
    locomotivecms (3.0.0.rc4) app/services/locomotive/page_parsing_service.rb:87:in `parse'
    locomotivecms (3.0.0.rc4) app/services/locomotive/page_parsing_service.rb:14:in `block (2 levels) in find_or_create_editable_elements'
    locomotivecms (3.0.0.rc4) app/services/locomotive/page_parsing_service.rb:51:in `subscribe'
    locomotivecms (3.0.0.rc4) app/services/locomotive/page_parsing_service.rb:13:in `block in find_or_create_editable_elements'
    activesupport (4.2.5) lib/active_support/benchmarkable.rb:41:in `block in benchmark'
    activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
    /Users/developer/.rbenv/versions/2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
    activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `ms'
    activesupport (4.2.5) lib/active_support/benchmarkable.rb:41:in `benchmark'
    locomotivecms (3.0.0.rc4) app/services/locomotive/page_parsing_service.rb:10:in `find_or_create_editable_elements'
    locomotivecms (3.0.0.rc4) app/controllers/locomotive/editable_elements_controller.rb:16:in `index'
    actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
    actionpack (4.2.5) lib/abstract_controller/base.rb:198:in `process_action'
    actionpack (4.2.5) lib/action_controller/metal/rendering.rb:10:in `process_action'
    actionpack (4.2.5) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
    activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'
    activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'
    activesupport (4.2.5) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
    activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
    activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
    activesupport (4.2.5) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
    activesupport (4.2.5) lib/active_support/callbacks.rb:292:in `call'
    activesupport (4.2.5) lib/active_support/callbacks.rb:292:in `block (2 levels) in halting_and_conditional'
    activesupport (4.2.5) lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
    locomotivecms (3.0.0.rc4) app/controllers/locomotive/concerns/timezone_controller.rb:8:in `set_timezone'
    activesupport (4.2.5) lib/active_support/callbacks.rb:432:in `block in make_lambda'
    activesupport (4.2.5) lib/active_support/callbacks.rb:291:in `call'
    activesupport (4.2.5) lib/active_support/callbacks.rb:291:in `block in halting_and_conditional'
    activesupport (4.2.5) lib/active_support/callbacks.rb:497:in `call'
    activesupport (4.2.5) lib/active_support/callbacks.rb:497:in `block in around'
    activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
    activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
    activesupport (4.2.5) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
    activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
    activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
    actionpack (4.2.5) lib/abstract_controller/callbacks.rb:19:in `process_action'
    actionpack (4.2.5) lib/action_controller/metal/rescue.rb:29:in `process_action'
    actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
    activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
    activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
    actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    actionpack (4.2.5) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
    actionpack (4.2.5) lib/abstract_controller/base.rb:137:in `process'
    actionview (4.2.5) lib/action_view/rendering.rb:30:in `process'
    actionpack (4.2.5) lib/action_controller/metal.rb:196:in `dispatch'
    actionpack (4.2.5) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
    actionpack (4.2.5) lib/action_controller/metal.rb:237:in `block in action'
    actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `call'
    actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
    actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:45:in `serve'
    actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
    actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `each'
    actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
    actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
    railties (4.2.5) lib/rails/engine.rb:518:in `call'
    railties (4.2.5) lib/rails/railtie.rb:194:in `public_send'
    railties (4.2.5) lib/rails/railtie.rb:194:in `method_missing'
    actionpack (4.2.5) lib/action_dispatch/routing/mapper.rb:51:in `serve'
    actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
    actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `each'
    actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
    actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
    locomotivecms (3.0.0.rc4) lib/locomotive/middlewares/site.rb:26:in `call'
    dragonfly (1.0.12) lib/dragonfly/middleware.rb:14:in `call'
    warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
    warden (1.2.3) lib/warden/manager.rb:34:in `catch'
    warden (1.2.3) lib/warden/manager.rb:34:in `call'
    rack (1.6.4) lib/rack/etag.rb:24:in `call'
    rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
    rack (1.6.4) lib/rack/head.rb:13:in `call'
    actionpack (4.2.5) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
    actionpack (4.2.5) lib/action_dispatch/middleware/flash.rb:260:in `call'
    rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
    rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
    actionpack (4.2.5) lib/action_dispatch/middleware/cookies.rb:560:in `call'
    actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
    activesupport (4.2.5) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
    activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
    activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
    actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
    actionpack (4.2.5) lib/action_dispatch/middleware/reloader.rb:73:in `call'
    actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
    actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
    web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
    actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
    railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
    railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
    activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
    activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
    activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
    railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
    actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
    rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
    rack (1.6.4) lib/rack/runtime.rb:18:in `call'
    activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
    dragonfly (1.0.12) lib/dragonfly/cookie_monster.rb:9:in `call'
    rack (1.6.4) lib/rack/lock.rb:17:in `call'
    actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
    rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
    railties (4.2.5) lib/rails/engine.rb:518:in `call'
    railties (4.2.5) lib/rails/application.rb:165:in `call'
    rack (1.6.4) lib/rack/content_length.rb:15:in `call'
    puma (2.15.3) lib/puma/server.rb:541:in `handle_request'
    puma (2.15.3) lib/puma/server.rb:388:in `process_client'
    puma (2.15.3) lib/puma/server.rb:270:in `block in run'
    puma (2.15.3) lib/puma/thread_pool.rb:106:in `call'
    puma (2.15.3) lib/puma/thread_pool.rb:106:in `block in spawn_thread'

Request

Parameters:

    {"site_handle"=>"pleasant-snowflake-6695",
     "page_id"=>"565a2c543a7dbc6f62000055"}

Session dump

    _csrf_token: "ML0xh5AkhRAfG+iko8H682GYCenms3RY/Jws42o7wng="
    content_locale: "en"
    return_to: "/locomotive/purring-sunshine-3336/content_types/photos/entries/5656779f3a7dbc016d00028d/edit"
    session_id: "285ebc21748548d13ca72b3fda9064af"
    warden.user.locomotive_account.key: ["565323dc3a7dbc180d000000", "VFzebTLx9yWbgzzcf9gy"]

Env dump

    GATEWAY_INTERFACE: "CGI/1.2"
    HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    HTTP_ACCEPT_ENCODING: "gzip, deflate, sdch"
    HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.8"
    REMOTE_ADDR: "::1"
    SERVER_NAME: "localhost"
    SERVER_PROTOCOL: "HTTP/1.1"

**Comment by CedricLor** [comment]
Correction, the version of the Engine is and steam is Correction: I do not have the latest version of the Wagon installed.

I have Engine 2.0.0.rc4 and Locomotive 1.0.0.rc6

**Comment by CedricLor** [comment]
I upgraded to the latest versions and this problems seems to have disappeared.
