### ISSUE TITLE
error pushing translations: Resource invalid: key is already taken

### ISSUE THREAD

**Issue by rvalyi** [locomotivecms/engine#1090]
I did
```
bundle exec wagon push production -v -d
```
and I don't understand why I have this error when pushing a translation. In my wagon website indexSlide1Title is used only once in a page and in config/translations.yml
I'm not sure if the error is in the engine part. Is there something I can do to help narrowing the issue?

```
Pushing Translations
  persisting press_endorsements [done]
  persisting contact [done]
  persisting our_address [done]
  persisting email [done]
  persisting phone [done]
  persisting indexSlide1Title [failed]
    Resource invalid: key is already taken
Resource invalid: key is already taken
	/var/lib/gems/2.2.0/gems/locomotivecms_coal-1.0.0.rc2/lib/locomotive/coal/resources/concerns/request.rb:36:in `do_request'
	/var/lib/gems/2.2.0/gems/locomotivecms_coal-1.0.0.rc2/lib/locomotive/coal/resources/concerns/request.rb:15:in `put'
	/var/lib/gems/2.2.0/gems/locomotivecms_coal-1.0.0.rc2/lib/locomotive/coal/resources/base.rb:30:in `update'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/commands/push_sub_commands/push_translations_command.rb:14:in `persist'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:32:in `block in _push'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:28:in `_push'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:23:in `block in _push_with_timezone'
	/var/lib/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:22:in `_push_with_timezone'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:16:in `block in push'
	/var/lib/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:45:in `instrument'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:14:in `push'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:10:in `push'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/commands/push_command.rb:54:in `block in _push'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/commands/push_command.rb:80:in `block in each_resource'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/commands/push_command.rb:73:in `each'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/commands/push_command.rb:73:in `each_resource'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/commands/push_command.rb:53:in `_push'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/commands/push_command.rb:36:in `push'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/commands/push_command.rb:30:in `push'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon.rb:73:in `push'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/lib/locomotive/wagon/cli.rb:313:in `deploy'
	/var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/home/akretion/.bundler/ruby/2.2.0/wagon-e1bc126968f6/bin/wagon:12:in `<top (required)>'
	/var/lib/gems/2.2.0/bin/wagon:23:in `load'
	/var/lib/gems/2.2.0/bin/wagon:23:in `<main>'
```

**Comment by CedricLor** [comment]
@rvalyi Can you please share your key for indexSlide1Title? I've had issues similar to this one in the past.

**Comment by did** [comment]
@rvalyi The translation keys should not include upper-case letters, spaces or hyphens.

**Comment by rvalyi** [comment]
@did thanks! that is why...
Now I suggest you put some kind of guard because for sure others will have the problem too and it's not obvious to find out the problem.

**Comment by did** [comment]
@rvalyi A warning message when you deploy OR in logs/wagon.log when you browse your Wagon site?

**Comment by rvalyi** [comment]
@did I would say both:
indeed there is a risk you miss the log when you develop. So at least a message why the push fails would definitely help.
