### ISSUE TITLE
[v3] Can't edit pages in back office after upgrading

### ISSUE THREAD

**Issue by DemitryT** [locomotivecms/engine#1114]
I just upgraded the locomotive cms to v3, which is still hooked up to the same mongodb that I was using on locomotive v2.5.6. I'm using Wagon v2.

When I try to edit the pages in the back office, I see "We’re sorry but we couldn’t parse the template the template of your page. Please make sure your templates first works with Wagon."

I upgraded Wagon to v2.0.0, launched the preview server and everything seems to be loading just fine, so I'm not sure what's going on.

The only clue I get in the logs is a wrong number of arguments error, when trying to initialize the block object from `locomotivecms-liquid-4.0.0`. I searched for docs of what needs to be updated in my templates or if anyone has come across this, no luck so far. Any ideas on this?

Here is what I'm seeing in my console during this error:
```
MONGODB | localhost:27017 | savedo_cms_development.find | STARTED | {"find"=>"locomotive_snippets", "filter"=>{"site_id"=>BSON::ObjectId('5514661e05054a8362000001'), "slug"=>"country_switcher"}}
MONGODB | localhost:27017 | savedo_cms_development.find | SUCCEEDED | 0.000475s
[LiveEditing] wrong number of arguments (4 for 3)
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:3:in `initialize'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_solid-0.2.2/lib/solid/element.rb:9:in `initialize'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/liquid/tags/with_scope.rb:30:in `initialize'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/tag.rb:9:in `new'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/tag.rb:9:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:27:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/document.rb:10:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/document.rb:5:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:124:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/liquid/template.rb:24:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/services/liquid_parser_service.rb:19:in `_parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/liquid/tags/snippet.rb:14:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/tag.rb:10:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:27:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:63:in `parse_body'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:10:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/inherited_block.rb:55:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/liquid/tags/inherited_block.rb:28:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/tag.rb:10:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:27:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:63:in `parse_body'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:10:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/inherited_block.rb:55:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/liquid/tags/inherited_block.rb:28:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/tag.rb:10:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:27:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/document.rb:10:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/document.rb:5:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:124:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/liquid/template.rb:24:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/services/liquid_parser_service.rb:19:in `_parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/services/liquid_parser_service.rb:9:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-3.0.0/lib/locomotive/steam/services/liquid_parser_with_cache_service.rb:11:in `parse'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/renderer.rb:33:in `parse_and_render_liquid'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/renderer.rb:22:in `render_page'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/renderer.rb:10:in `_call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-3.0.0/lib/locomotive/steam/middlewares/cache.rb:19:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-3.0.0/lib/locomotive/steam/middlewares/catch_error.rb:13:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-3.0.0/lib/locomotive/steam/middlewares/page_editing.rb:14:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-3.0.0/lib/locomotive/steam/middlewares/missing_translations.rb:13:in `block in call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-3.0.0/lib/locomotive/steam/middlewares/missing_translations.rb:24:in `find_and_persist_missing_translations'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-3.0.0/lib/locomotive/steam/middlewares/missing_translations.rb:12:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-3.0.0/lib/locomotive/steam/middlewares/wysihtml_css.rb:12:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/path.rb:13:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/locale.rb:24:in `block in _call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/locale.rb:23:in `_call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/timezone.rb:16:in `block in _call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/activesupport-4.2.5/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/timezone.rb:15:in `_call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/robots.rb:15:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/logging.rb:18:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/default_env.rb:15:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/dragonfly-1.0.12/lib/dragonfly/middleware.rb:14:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms_steam-1.0.0/lib/locomotive/steam/middlewares/favicon.rb:15:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/routing/mapper.rb:51:in `serve'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:43:in `block in serve'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `each'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `serve'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:817:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/railties-4.2.5/lib/rails/engine.rb:518:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/railties-4.2.5/lib/rails/railtie.rb:194:in `public_send'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/railties-4.2.5/lib/rails/railtie.rb:194:in `method_missing'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/routing/mapper.rb:51:in `serve'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:43:in `block in serve'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `each'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `serve'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:817:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-3.0.0/lib/locomotive/middlewares/site.rb:26:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/dragonfly-1.0.12/lib/dragonfly/middleware.rb:14:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/warden-1.2.4/lib/warden/manager.rb:35:in `block in call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/warden-1.2.4/lib/warden/manager.rb:34:in `catch'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/warden-1.2.4/lib/warden/manager.rb:34:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/middleware/flash.rb:260:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/middleware/cookies.rb:560:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/middleware/reloader.rb:73:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/airbrake-4.3.5/lib/airbrake/rails/middleware.rb:13:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/railties-4.2.5/lib/rails/rack/logger.rb:38:in `call_app'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `block in call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `block in tagged'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:26:in `tagged'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `tagged'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/middleware/request_id.rb:21:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/activesupport-4.2.5/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/dragonfly-1.0.12/lib/dragonfly/cookie_monster.rb:9:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/locomotivecms-3.0.0/lib/locomotive/middlewares/image_thumbnail.rb:23:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/actionpack-4.2.5/lib/action_dispatch/middleware/static.rb:116:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/airbrake-4.3.5/lib/airbrake/user_informer.rb:16:in `_call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/airbrake-4.3.5/lib/airbrake/user_informer.rb:12:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/railties-4.2.5/lib/rails/engine.rb:518:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/railties-4.2.5/lib/rails/application.rb:165:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
	/Users/demitryt/.rvm/gems/ruby-2.1.6@savedo-cms/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/Users/demitryt/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	/Users/demitryt/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	/Users/demitryt/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by DemitryT** [comment]
Hey @did,

I tried  the solution you offered on gitter, but running into another issue now. My old site never had a subdomain attribute, so after running the upgrade rake task, the handle is not set for the old site.

I can easily set the handle for the old site in the rails console, but I was wondering if you see any issues with this.

**Comment by did** [comment]
@DemitryT hmm, you were using Locomotive in the non-multi-sites mode, right?

**Comment by DemitryT** [comment]
Yes, that's correct. I just set the handle manually and now I can load the site in the back office, but the editable content is still not loading and the site is not loading as well.

It seems as though both of the issues are coming from the` locomotivecms-liquid` gem, when it tries to initialize the Block object. So I'm seeing "wrong number of arguments (4 for 3)" for the stack trace below.

<img width="1043" alt="screen shot 2016-01-21 at 11 38 01 am" src="https://cloud.githubusercontent.com/assets/498697/12478145/9ed12a9e-c033-11e5-9a36-f089dc9d3221.png">

Currently looking into this, but just as a side note, I'm using the hosting branch with the "locomotivecms_liquid_extensions" gem.

**Comment by did** [comment]
@DemitryT 

1/ I will modify the rake task to set a random handle if there is no subdomain

2/ could you remove the **locomotivecms_liquid_extensions** gem please and see if it works. We back ported all the filters from this gem in Steam. We didn't include the send_email, create and update tags. We'll replace them by another component.

**Comment by DemitryT** [comment]
Great, thanks! Removing `locomotivecms_liquid_extensions` does the trick.

However, if we created our own filter for Liquid and registered it globally, is there documentation on how to achieve the same behavior now?

**Comment by did** [comment]
@DemitryT you still can create your own filter for Liquid, the same way you did before. Does your Liquid filters involve access to content entries or other models?

**Comment by DemitryT** [comment]
The access should just be to content entries. I see that you're registering filters in the steam gem, so I'll see how it's done there and try to update my code.

**Comment by did** [comment]
The code is Steam is pretty clear. 
So, if you need to access content entries, use the content entries repository (you've got access to it through the **services** liquid register). Using the right repository ensures that your code will work in both Engine and Wagon. That's very important.
Let me know if you can't achieve what you've got in mind.

**Comment by DemitryT** [comment]
Got it, thanks for the info.

I copied the module structure you have [here](https://github.com/locomotivecms/steam/blob/master/lib/locomotive/steam/liquid/filters/json.rb) for registering a filter instead of the previous way I did it. Everything works now.

Thanks again!
