### ISSUE TITLE
order_by

### ISSUE THREAD

**Issue by benoist** [locomotivecms/engine#1119]
Hi,

Is it possible to change the content_entry order_by using something like with_scope?

I'm having to order upcoming events with asc and previous events with desc, but I can't find how to do that.

**Comment by adam-pl** [comment]
1. Open [with_scope  docs](https://locomotive-v3.readme.io/docs/tags#with_scope)
1. Go to the `Examples` section
1. Click `ordering`
1. You' ve found the answer :-)

**Comment by benoist** [comment]
Ah the contrast is a bit low, so didn't really notice it had more examples :)

Thank you!

**Comment by benoist** [comment]
According to the docs it's should be 'starting_time.desc' but that crashed. 'starting_time DESC' worked (using origin 2.1.1)

**Comment by did** [comment]
@benoist. Let me check that, I think "starting_time.desc" should work. What's the error you get?

**Comment by benoist** [comment]
In the template I use 

```liquid
{% with_scope start_time.gte: today, order_by: 'start_time.asc' %}
```

This is the stack trace

```
NoMethodError (undefined method `to_direction' for nil:NilClass):
  origin (2.2.0) lib/origin/extensions/string.rb:57:in `block (2 levels) in __sort_option__'
  origin (2.2.0) lib/origin/extensions/string.rb:55:in `tap'
  origin (2.2.0) lib/origin/extensions/string.rb:55:in `block in __sort_option__'
  origin (2.2.0) lib/origin/extensions/string.rb:54:in `each'
  origin (2.2.0) lib/origin/extensions/string.rb:54:in `inject'
  origin (2.2.0) lib/origin/extensions/string.rb:54:in `__sort_option__'
  origin (2.2.0) lib/origin/optional.rb:173:in `block (2 levels) in order_by'
  origin (2.2.0) lib/origin/optional.rb:172:in `each'
  origin (2.2.0) lib/origin/optional.rb:172:in `block in order_by'
  origin (2.2.0) lib/origin/optional.rb:350:in `block in option'
  origin (2.2.0) lib/origin/optional.rb:348:in `tap'
  origin (2.2.0) lib/origin/optional.rb:348:in `option'
  origin (2.2.0) lib/origin/optional.rb:171:in `order_by'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/adapters/mongodb/query.rb:60:in `to_origin'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/adapters/mongodb/query.rb:47:in `against'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/adapters/mongodb.rb:70:in `block in dataset'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/adapters/mongodb/dataset.rb:8:in `initialize'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/adapters/mongodb.rb:69:in `new'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/adapters/mongodb.rb:69:in `dataset'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/adapters/mongodb.rb:16:in `all'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/adapters/mongodb.rb:21:in `query'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/models/repository.rb:44:in `query'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/repositories/content_entry_repository.rb:43:in `all'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/liquid/drops/content_entry_collection.rb:59:in `collection'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/liquid/drops/content_entry_collection.rb:8:in `each'
  locomotivecms-liquid (4.0.0) lib/liquid/utils.rb:23:in `slice_collection_using_each'
  locomotivecms-liquid (4.0.0) lib/liquid/utils.rb:8:in `slice_collection'
  locomotivecms-liquid (4.0.0) lib/liquid/tags/for.rb:88:in `render'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:105:in `render_token'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:87:in `block in render'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `each'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `render'
  locomotivecms-liquid (4.0.0) lib/liquid/block.rb:15:in `render'
  locomotivecms-solid (4.0.1) lib/solid/block.rb:8:in `block (2 levels) in render'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/liquid/tags/with_scope.rb:37:in `block in display'
  locomotivecms-liquid (4.0.0) lib/liquid/context.rb:128:in `stack'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/liquid/tags/with_scope.rb:34:in `display'
  locomotivecms-solid (4.0.1) lib/solid/block.rb:7:in `block in render'
  locomotivecms-solid (4.0.1) lib/solid/element.rb:20:in `with_context'
  locomotivecms-solid (4.0.1) lib/solid/block.rb:6:in `render'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:105:in `render_token'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:87:in `block in render'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `each'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `render'
  locomotivecms-liquid (4.0.0) lib/liquid/block.rb:15:in `render'
  locomotivecms-liquid (4.0.0) lib/liquid/tags/inherited_block.rb:71:in `block in render'
  locomotivecms-liquid (4.0.0) lib/liquid/context.rb:128:in `stack'
  locomotivecms-liquid (4.0.0) lib/liquid/tags/inherited_block.rb:64:in `render'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/liquid/tags/inherited_block.rb:42:in `render'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:105:in `render_token'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:87:in `block in render'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `each'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `render'
  locomotivecms-liquid (4.0.0) lib/liquid/block.rb:15:in `render'
  locomotivecms-liquid (4.0.0) lib/liquid/tags/inherited_block.rb:71:in `block in render'
  locomotivecms-liquid (4.0.0) lib/liquid/context.rb:128:in `stack'
  locomotivecms-liquid (4.0.0) lib/liquid/tags/inherited_block.rb:64:in `render'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/liquid/tags/inherited_block.rb:42:in `render'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:105:in `render_token'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:87:in `block in render'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `each'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `render'
  locomotivecms-liquid (4.0.0) lib/liquid/block.rb:15:in `render'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/liquid/tags/extends.rb:10:in `block in render'
  locomotivecms-liquid (4.0.0) lib/liquid/context.rb:128:in `stack'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/liquid/tags/extends.rb:8:in `render'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:105:in `render_token'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:87:in `block in render'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `each'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `render'
  locomotivecms-liquid (4.0.0) lib/liquid/block.rb:15:in `render'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/liquid/tags/extends.rb:10:in `block in render'
  locomotivecms-liquid (4.0.0) lib/liquid/context.rb:128:in `stack'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/liquid/tags/extends.rb:8:in `render'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:105:in `render_token'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:87:in `block in render'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `each'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `render'
  locomotivecms-liquid (4.0.0) lib/liquid/template.rb:215:in `block in render'
  locomotivecms-liquid (4.0.0) lib/liquid/template.rb:269:in `with_profiling'
  locomotivecms-liquid (4.0.0) lib/liquid/template.rb:214:in `render'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/liquid/template.rb:17:in `render'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/renderer.rb:34:in `parse_and_render_liquid'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/renderer.rb:22:in `render_page'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/renderer.rb:10:in `_call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
  locomotivecms (3.0.0) lib/locomotive/steam/middlewares/cache.rb:19:in `call'
  locomotivecms (3.0.0) lib/locomotive/steam/middlewares/catch_error.rb:13:in `call'
  locomotivecms (3.0.0) lib/locomotive/steam/middlewares/page_editing.rb:14:in `call'
  locomotivecms (3.0.0) lib/locomotive/steam/middlewares/missing_translations.rb:13:in `block in call'
  locomotivecms (3.0.0) lib/locomotive/steam/middlewares/missing_translations.rb:24:in `find_and_persist_missing_translations'
  locomotivecms (3.0.0) lib/locomotive/steam/middlewares/missing_translations.rb:12:in `call'
  locomotivecms (3.0.0) lib/locomotive/steam/middlewares/wysihtml_css.rb:12:in `call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/path.rb:13:in `call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/locale.rb:24:in `block in _call'
  i18n (0.7.0) lib/i18n.rb:257:in `with_locale'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/locale.rb:23:in `_call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/timezone.rb:16:in `block in _call'
  activesupport (4.2.5) lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/timezone.rb:15:in `_call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/robots.rb:15:in `call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/logging.rb:18:in `call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/default_env.rb:15:in `call'
  dragonfly (1.0.12) lib/dragonfly/middleware.rb:14:in `call'
  locomotivecms_steam (1.0.0) lib/locomotive/steam/middlewares/favicon.rb:15:in `call'
  rack-rewrite (1.5.1) lib/rack/rewrite.rb:24:in `call'
  rack (1.6.4) lib/rack/builder.rb:153:in `call'
  actionpack (4.2.5) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
  locomotivecms (3.0.0) lib/locomotive/middlewares/site.rb:26:in `call'
  dragonfly (1.0.12) lib/dragonfly/middleware.rb:14:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `catch'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  locomotivecms (3.0.0) lib/locomotive/middlewares/image_thumbnail.rb:23:in `call'
  dragonfly (1.0.12) lib/dragonfly/cookie_monster.rb:9:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (2.16.0) lib/puma/server.rb:557:in `handle_request'
  puma (2.16.0) lib/puma/server.rb:404:in `process_client'
  puma (2.16.0) lib/puma/server.rb:270:in `block in run'
  puma (2.16.0) lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by did** [comment]
@benoist That should fix your error :-) thanks for the bug report.

**Comment by benoist** [comment]
:+1:
