### ISSUE TITLE
Errno::ENAMETOOLONG in Locomotive::CustomFields::SelectOptionsController#edit

### ISSUE THREAD

**Issue by crhowell** [locomotivecms/engine#1123]
I am getting an error in development when editing select_options in the locomotive back-end. I think it is related to Rails caching because when I turn `config.cache_store = :null_store` in `config/environments/development.rb` the error goes away. It may be related to the cache `_key` created at this line in [`lib/locomotive/simple_form.rb`](https://github.com/locomotivecms/engine/blob/master/lib/locomotive/simple_form.rb#L42). It looks like that `_key` is too long for a temp filename. 

Here is a stack trace
```
Errno::ENAMETOOLONG in Locomotive::CustomFields::SelectOptionsController#edit
File name too long @ rb_sysopen - /home/chrisrh/Projects/ruby/loco-engine/tmp/cache/en%2Flocomotive%2Fcustom_fields%2Fselect_options%2Fedit%2Fplaceholders%2Flocomotive.content_type_entry_field%2Fselect_options20160205-2688-kkjbtm
Extracted source (around line #136):

134 mode |= File::RDWR|File::CREAT|File::EXCL
135 opts[:perm] = 0600
136 @data[1] = @tmpfile = File.open(tmpname, mode, opts)
137 @data[0] = @tmpname = tmpname
138 @mode = mode & ~(File::CREAT|File::EXCL)
139 opts.freeze

Rails.root: /home/chrisrh/Projects/ruby/loco-engine
Application Trace | Framework Trace | Full Trace

/home/chrisrh/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tempfile.rb:136:in `initialize'
/home/chrisrh/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tempfile.rb:136:in `open'
/home/chrisrh/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tempfile.rb:136:in `block in initialize'
/home/chrisrh/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tmpdir.rb:129:in `create'
/home/chrisrh/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tempfile.rb:133:in `initialize'
activesupport (4.2.5.1) lib/active_support/core_ext/file/atomic.rb:21:in `new'
activesupport (4.2.5.1) lib/active_support/core_ext/file/atomic.rb:21:in `atomic_write'
activesupport (4.2.5.1) lib/active_support/cache/file_store.rb:83:in `write_entry'
activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache.rb:115:in `write_entry'
activesupport (4.2.5.1) lib/active_support/cache.rb:391:in `block in write'
activesupport (4.2.5.1) lib/active_support/cache.rb:547:in `block in instrument'
activesupport (4.2.5.1) lib/active_support/notifications.rb:166:in `instrument'
activesupport (4.2.5.1) lib/active_support/cache.rb:547:in `instrument'
activesupport (4.2.5.1) lib/active_support/cache.rb:389:in `write'
activesupport (4.2.5.1) lib/active_support/cache.rb:588:in `save_block_result_to_cache'
activesupport (4.2.5.1) lib/active_support/cache.rb:299:in `fetch'
locomotivecms (3.0.0) lib/locomotive/simple_form.rb:49:in `translate_from_namespace'
simple_form (3.2.1) lib/simple_form/components/placeholders.rb:12:in `placeholder_text'
simple_form (3.2.1) lib/simple_form/components/placeholders.rb:6:in `placeholder'
simple_form (3.2.1) lib/simple_form/wrappers/leaf.rb:19:in `call'
simple_form (3.2.1) lib/simple_form/wrappers/leaf.rb:19:in `render'
simple_form (3.2.1) lib/simple_form/wrappers/many.rb:28:in `block in render'
simple_form (3.2.1) lib/simple_form/wrappers/many.rb:26:in `each'
simple_form (3.2.1) lib/simple_form/wrappers/many.rb:26:in `render'
simple_form (3.2.1) lib/simple_form/wrappers/many.rb:28:in `block in render'
simple_form (3.2.1) lib/simple_form/wrappers/many.rb:26:in `each'
simple_form (3.2.1) lib/simple_form/wrappers/many.rb:26:in `render'
simple_form (3.2.1) lib/simple_form/wrappers/root.rb:15:in `render'
simple_form (3.2.1) lib/simple_form/form_builder.rb:116:in `input'
locomotivecms (3.0.0) app/views/locomotive/custom_fields/select_options/edit.html.slim:6:in `block (2 levels) in __home_chrisrh__rbenv_versions_______lib_ruby_gems_______gems_locomotivecms_______app_views_locomotive_custom_fields_select_options_edit_html_slim___1446623602946651085_70357694211820'
actionview (4.2.5.1) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionview (4.2.5.1) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
actionview (4.2.5.1) lib/action_view/helpers/capture_helper.rb:38:in `capture'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
locomotivecms (3.0.0) lib/locomotive/simple_form.rb:74:in `inputs'
locomotivecms (3.0.0) app/views/locomotive/custom_fields/select_options/edit.html.slim:5:in `block in __home_chrisrh__rbenv_versions_______lib_ruby_gems_______gems_locomotivecms_______app_views_locomotive_custom_fields_select_options_edit_html_slim___1446623602946651085_70357694211820'
actionview (4.2.5.1) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionview (4.2.5.1) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
actionview (4.2.5.1) lib/action_view/helpers/capture_helper.rb:38:in `capture'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
actionview (4.2.5.1) lib/action_view/helpers/form_helper.rb:444:in `form_for'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:139:in `form_for_with_haml'
haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:28:in `form_for_with_haml_xss'
simple_form (3.2.1) lib/simple_form/action_view_extensions/form_helper.rb:26:in `block in simple_form_for'
simple_form (3.2.1) lib/simple_form/action_view_extensions/form_helper.rb:45:in `with_simple_form_field_error_proc'
simple_form (3.2.1) lib/simple_form/action_view_extensions/form_helper.rb:25:in `simple_form_for'
locomotivecms (3.0.0) app/helpers/locomotive/base_helper.rb:41:in `locomotive_form_for'
locomotivecms (3.0.0) app/views/locomotive/custom_fields/select_options/edit.html.slim:3:in `__home_chrisrh__rbenv_versions_______lib_ruby_gems_______gems_locomotivecms_______app_views_locomotive_custom_fields_select_options_edit_html_slim___1446623602946651085_70357694211820'
actionview (4.2.5.1) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.5.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.5.1) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.5.1) lib/action_view/template.rb:143:in `render'
actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (4.2.5.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `instrument'
actionview (4.2.5.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (4.2.5.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (4.2.5.1) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (4.2.5.1) lib/action_view/rendering.rb:100:in `_render_template'
actionpack (4.2.5.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.2.5.1) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (4.2.5.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.2.5.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
actionpack (4.2.5.1) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.2.5.1) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (4.2.5.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/chrisrh/.rbenv/versions/2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
activesupport (4.2.5.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
responders (2.1.1) lib/action_controller/responder.rb:236:in `default_render'
responders (2.1.1) lib/action_controller/responder.rb:170:in `to_html'
responders (2.1.1) lib/responders/flash_responder.rb:107:in `to_html'
locomotivecms (3.0.0) lib/locomotive/action_controller/responder.rb:23:in `to_html'
responders (2.1.1) lib/action_controller/responder.rb:163:in `respond'
responders (2.1.1) lib/action_controller/responder.rb:156:in `call'
responders (2.1.1) lib/action_controller/respond_with.rb:205:in `respond_with'
locomotivecms (3.0.0) app/controllers/locomotive/custom_fields/select_options_controller.rb:9:in `edit'
actionpack (4.2.5.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.5.1) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.5.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.5.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.5.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
actionpack (4.2.5.1) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.5.1) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.5.1) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.5.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.5.1) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:815:in `call'
railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
railties (4.2.5.1) lib/rails/railtie.rb:194:in `public_send'
railties (4.2.5.1) lib/rails/railtie.rb:194:in `method_missing'
actionpack (4.2.5.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:815:in `call'
locomotivecms (3.0.0) lib/locomotive/middlewares/site.rb:26:in `call'
dragonfly (1.0.12) lib/dragonfly/middleware.rb:14:in `call'
warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
warden (1.2.6) lib/warden/manager.rb:34:in `catch'
warden (1.2.6) lib/warden/manager.rb:34:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
locomotivecms (3.0.0) lib/locomotive/middlewares/image_thumbnail.rb:23:in `call'
dragonfly (1.0.12) lib/dragonfly/cookie_monster.rb:9:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/static.rb:116:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
railties (4.2.5.1) lib/rails/application.rb:165:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
puma (2.16.0) lib/puma/server.rb:557:in `handle_request'
puma (2.16.0) lib/puma/server.rb:404:in `process_client'
puma (2.16.0) lib/puma/server.rb:270:in `block in run'
puma (2.16.0) lib/puma/thread_pool.rb:106:in `call'
puma (2.16.0) lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

Let me know If I can help clarify,
Thank you for all your work on V3.

**Comment by did** [comment]
hi @crhowell, I've no problem to digest the key. What do you think about that?

**Comment by crhowell** [comment]
Hi @did, after some vigorous searching and troubleshooting. I no longer believe this is an issue with Locomotive. I believe this is more of a conflict between Rails caching and file system encryption.

I think the reason you were not reproducing this error is because my project folders are located within my home directory, which happens to be encrypted.

I can solve this issue two ways:

1. Move project folder off the encrypted partition (out of my home directory). The error goes away.

2. Leave it on my encrypted partition and I must use a **silence_warnings** initializer.

I used "binary search" on the FILENAME_MAX_SIZE constant to pin-point where exactly the failing point occurred. It seems 124 is the maximum I can go to have it still work. 125 will fail.

```ruby
  silence_warnings do
    # works ActiveSupport::Cache::FileStore::FILENAME_MAX_SIZE = 116
    # works ActiveSupport::Cache::FileStore::FILENAME_MAX_SIZE = 120
    # works ActiveSupport::Cache::FileStore::FILENAME_MAX_SIZE = 122
    # works
    ActiveSupport::Cache::FileStore::FILENAME_MAX_SIZE = 124
    # fails ActiveSupport::Cache::FileStore::FILENAME_MAX_SIZE = 125
    # fails ActiveSupport::Cache::FileStore::FILENAME_MAX_SIZE = 135
    # fails ActiveSupport::Cache::FileStore::FILENAME_MAX_SIZE = 144
    # fails ActiveSupport::Cache::FileStore::FILENAME_MAX_SIZE = 172
    # fails ActiveSupport::Cache::FileStore::FILENAME_MAX_SIZE = 228
  end
  ```

**Comment by did** [comment]
@crhowell thanks for keeping me posted on this one. I'm sure it will help someone someday ;-)
I think you should definitively move your app off the encrypted partition. I will only leave MongoDB files on that partition.

**Comment by rvalyi** [comment]
just to mention your report just saved me hours of googling while testing Akretion Shopinvader, I will see with @sebastienbeau what is the best way to fix this in our default docker-compose file. In our case we have to use some directory like /tmp/shopinvader from the host to mount as the app tmp directory to avoid this issue. Will reference this soon. So thank you for the report anyway.

**Comment by manuchap** [comment]
shopinvader & odoo docker to be updated this week from what I know.
patience will be rewarded :-)
