### ISSUE TITLE
Site metafields aren't working with type = file

### ISSUE THREAD

**Issue by jwigal** [locomotivecms/engine#1162]
Using `locomotivecms` gem 3.1.1 and `locomotive_wagon` version 2.1.1.

I'm trying to add a site metafield with a type of `file`, and here's what I'm seeing:

* Create a new site with wagon
* In metafields_schema.yml, I have this:

```
site_options:
  fields:
    my_logo:
      type: file
```
* use `wagon deploy development` to deploy the new site to local instance of locomotive (this creates a new site)
* navigate to **Properties** for the site (`/locomotive/wooden-sanctuary-8395/current_site_metafields`)
* I get the following Exception:

```
NoMethodError in Locomotive::CurrentSiteMetafieldsController#index
undefined method `my_logo?' for #<Locomotive::CurrentSiteMetafieldsHelper::SchemaGroup:0x007fd75b4bf9d0>
```
with the following abbreviated stack trace:

```
locomotivecms (3.1.1) app/helpers/locomotive/current_site_metafields_helper.rb:44:in `method_missing'
locomotivecms (3.1.1) app/inputs/locomotive/file_input.rb:94:in `persisted_file?'
locomotivecms (3.1.1) app/inputs/locomotive/file_input.rb:11:in `input'
simple_form (3.2.1) lib/simple_form/wrappers/leaf.rb:19:in `call'
simple_form (3.2.1) lib/simple_form/wrappers/leaf.rb:19:in `render'
simple_form (3.2.1) lib/simple_form/wrappers/many.rb:28:in `block in render'
simple_form (3.2.1) lib/simple_form/wrappers/many.rb:26:in `each'
simple_form (3.2.1) lib/simple_form/wrappers/many.rb:26:in `render'
simple_form (3.2.1) lib/simple_form/wrappers/many.rb:28:in `block in render'
simple_form (3.2.1) lib/simple_form/wrappers/many.rb:26:in `each'
simple_form (3.2.1) lib/simple_form/wrappers/many.rb:26:in `render'
simple_form (3.2.1) lib/simple_form/wrappers/root.rb:15:in `render'
simple_form (3.2.1) lib/simple_form/form_builder.rb:116:in `input'
locomotivecms (3.1.1) app/views/locomotive/current_site_metafields/form/_panes.html.slim:14:in `block (6 levels) in ___sers_jeff__rvm_gems_ruby_______gems_locomotivecms_______app_views_locomotive_current_site_metafields_form__panes_html_slim__997627265018944693_70281384048460'
locomotivecms (3.1.1) app/views/locomotive/current_site_metafields/form/_panes.html.slim:12:in `each'
locomotivecms (3.1.1) app/views/locomotive/current_site_metafields/form/_panes.html.slim:12:in `block (5 levels) in ___sers_jeff__rvm_gems_ruby_______gems_locomotivecms_______app_views_locomotive_current_site_metafields_form__panes_html_slim__997627265018944693_70281384048460'
actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `capture'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
actionview (4.2.6) lib/action_view/helpers/form_helper.rb:714:in `fields_for'
actionview (4.2.6) lib/action_view/helpers/form_helper.rb:1599:in `fields_for'
simple_form (3.2.1) lib/simple_form/action_view_extensions/builder.rb:27:in `simple_fields_for'
locomotivecms (3.1.1) app/views/locomotive/current_site_metafields/form/_panes.html.slim:10:in `block (4 levels) in ___sers_jeff__rvm_gems_ruby_______gems_locomotivecms_______app_views_locomotive_current_site_metafields_form__panes_html_slim__997627265018944693_70281384048460'
actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `capture'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
locomotivecms (3.1.1) lib/locomotive/simple_form.rb:75:in `inputs'
locomotivecms (3.1.1) app/views/locomotive/current_site_metafields/form/_panes.html.slim:8:in `block (3 levels) in ___sers_jeff__rvm_gems_ruby_______gems_locomotivecms_______app_views_locomotive_current_site_metafields_form__panes_html_slim__997627265018944693_70281384048460'
actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `capture'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
locomotivecms (3.1.1) app/helpers/locomotive/base_helper.rb:70:in `form_tab_pane'
locomotivecms (3.1.1) app/views/locomotive/current_site_metafields/form/_panes.html.slim:6:in `block (2 levels) in ___sers_jeff__rvm_gems_ruby_______gems_locomotivecms_______app_views_locomotive_current_site_metafields_form__panes_html_slim__997627265018944693_70281384048460'
locomotivecms (3.1.1) app/views/locomotive/current_site_metafields/form/_panes.html.slim:4:in `each'
locomotivecms (3.1.1) app/views/locomotive/current_site_metafields/form/_panes.html.slim:4:in `each_with_index'
locomotivecms (3.1.1) app/views/locomotive/current_site_metafields/form/_panes.html.slim:4:in `block in ___sers_jeff__rvm_gems_ruby_______gems_locomotivecms_______app_views_locomotive_current_site_metafields_form__panes_html_slim__997627265018944693_70281384048460'
actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `capture'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
actionview (4.2.6) lib/action_view/helpers/form_helper.rb:714:in `fields_for'
actionview (4.2.6) lib/action_view/helpers/form_helper.rb:1599:in `fields_for'
simple_form (3.2.1) lib/simple_form/action_view_extensions/builder.rb:27:in `simple_fields_for'
locomotivecms (3.1.1) app/views/locomotive/current_site_metafields/form/_panes.html.slim:2:in `___sers_jeff__rvm_gems_ruby_______gems_locomotivecms_______app_views_locomotive_current_site_metafields_form__panes_html_slim__997627265018944693_70281384048460'
actionview (4.2.6) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.6) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.6) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.6) lib/action_view/template.rb:143:in `render'
actionview (4.2.6) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
actionview (4.2.6) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
actionview (4.2.6) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
actionview (4.2.6) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
actionview (4.2.6) lib/action_view/renderer/partial_renderer.rb:309:in `render'
actionview (4.2.6) lib/action_view/renderer/renderer.rb:51:in `render_partial'
actionview (4.2.6) lib/action_view/helpers/rendering_helper.rb:35:in `render'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
locomotivecms (3.1.1) app/views/locomotive/current_site_metafields/index.html.slim:19:in `block in ___sers_jeff__rvm_gems_ruby_______gems_locomotivecms_______app_views_locomotive_current_site_metafields_index_html_slim___4580568010085980963_70281454533920'
actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
actionview (4.2.6) lib/action_view/helpers/capture_helper.rb:38:in `capture'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
actionview (4.2.6) lib/action_view/helpers/form_helper.rb:444:in `form_for'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:139:in `form_for_with_haml'
haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:28:in `form_for_with_haml_xss'
simple_form (3.2.1) lib/simple_form/action_view_extensions/form_helper.rb:26:in `block in simple_form_for'
simple_form (3.2.1) lib/simple_form/action_view_extensions/form_helper.rb:45:in `with_simple_form_field_error_proc'
simple_form (3.2.1) lib/simple_form/action_view_extensions/form_helper.rb:25:in `simple_form_for'
locomotivecms (3.1.1) app/helpers/locomotive/base_helper.rb:57:in `locomotive_form_for'
locomotivecms (3.1.1) app/views/locomotive/current_site_metafields/index.html.slim:11:in `___sers_jeff__rvm_gems_ruby_______gems_locomotivecms_______app_views_locomotive_current_site_metafields_index_html_slim___4580568010085980963_70281454533920'
actionview (4.2.6) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.6) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.6) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.6) lib/action_view/template.rb:143:in `render'
actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (4.2.6) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
actionview (4.2.6) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (4.2.6) lib/action_view/renderer/renderer.rb:46:in `render_template'
actionview (4.2.6) lib/action_view/renderer/renderer.rb:27:in `render'
actionview (4.2.6) lib/action_view/rendering.rb:100:in `_render_template'
actionpack (4.2.6) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.2.6) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (4.2.6) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.2.6) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
actionpack (4.2.6) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.2.6) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
[snip]
```

**Comment by jwigal** [comment]
Just noticed an additional type of `image`, when I use that it seems to work fine. 

That's what I wanted to use anyway, so I think I'm good, but it may still be broken if someone wants to use the `file` type.

**Comment by did** [comment]
@jwigal good point. I removed the "file" type from the list in the generated metafield_schema.yml file of a Wagon site.
