### ISSUE TITLE
Crash retrieving a page

### ISSUE THREAD

**Issue by justmark** [locomotivecms/engine#1170]
Running Locomotive 3.1.1

After the system starts and I try and access any page, the logs start repeating the following:

```
MONGODB | localhost:27017 | locomotiveapp_dev.find | STARTED | {"find"=>"locomotive_pages", "filter"=>{"site_id"=>BSON::ObjectId('572371881dd64738101f45f6'), "fullpath.en"=>{"$in"=>["index", "content_type_template"]}}, "sort"=>{"depth"=>1, "position"=>1}}
MONGODB | localhost:27017 | locomotiveapp_dev.find | SUCCEEDED | 0.0008707869999999999s
MONGODB | localhost:27017 | locomotiveapp_dev.find | STARTED | {"find"=>"locomotive_pages", "filter"=>{"site_id"=>BSON::ObjectId('572371881dd64738101f45f6'), "fullpath.en"=>"timeline"}}
MONGODB | localhost:27017 | locomotiveapp_dev.find | SUCCEEDED | 0.000788922s
MONGODB | localhost:27017 | locomotiveapp_dev.find | STARTED | {"find"=>"locomotive_pages", "filter"=>{"site_id"=>BSON::ObjectId('572371881dd64738101f45f6'), "_id"=>BSON::ObjectId('572371881dd64738101f45f8')}}
MONGODB | localhost:27017 | locomotiveapp_dev.find | SUCCEEDED | 0.0007946s
MONGODB | localhost:27017 | locomotiveapp_dev.find | STARTED | {"find"=>"locomotive_pages", "filter"=>{"site_id"=>BSON::ObjectId('572371881dd64738101f45f6'), "fullpath.en"=>"timeline"}}
MONGODB | localhost:27017 | locomotiveapp_dev.find | SUCCEEDED | 0.0009419340000000001s
MONGODB | localhost:27017 | locomotiveapp_dev.find | STARTED | {"find"=>"locomotive_pages", "filter"=>{"site_id"=>BSON::ObjectId('572371881dd64738101f45f6'), "_id"=>BSON::ObjectId('572371881dd64738101f45f8')}}
MONGODB | localhost:27017 | locomotiveapp_dev.find | SUCCEEDED | 0.00072209s
MONGODB | localhost:27017 | locomotiveapp_dev.find | STARTED | {"find"=>"locomotive_pages", "filter"=>{"site_id"=>BSON::ObjectId('572371881dd64738101f45f6'), "fullpath.en"=>"timeline"}}
MONGODB | localhost:27017 | locomotiveapp_dev.find | SUCCEEDED | 0.000766563s
```

This keeps repeating roughly a thousand times, and results in a crash:

```
SystemStackError (stack level too deep):
  bson (4.1.1) lib/bson/array.rb:96:in `from_bson'
  bson (4.1.1) lib/bson/hash.rb:80:in `from_bson'
  mongo (2.2.7) lib/mongo/dbref.rb:103:in `from_bson'
  bson (4.1.1) lib/bson/hash.rb:80:in `from_bson'
  mongo (2.2.7) lib/mongo/dbref.rb:103:in `from_bson'
  mongo (2.2.7) lib/mongo/protocol/serializers.rb:175:in `deserialize'
  mongo (2.2.7) lib/mongo/protocol/message.rb:279:in `block in deserialize_array'
  mongo (2.2.7) lib/mongo/protocol/message.rb:279:in `times'
  mongo (2.2.7) lib/mongo/protocol/message.rb:279:in `deserialize_array'
  mongo (2.2.7) lib/mongo/protocol/message.rb:132:in `block in deserialize'
  mongo (2.2.7) lib/mongo/protocol/message.rb:130:in `each'
  mongo (2.2.7) lib/mongo/protocol/message.rb:130:in `deserialize'
  mongo (2.2.7) lib/mongo/server/connectable.rb:108:in `block in read'
  mongo (2.2.7) lib/mongo/server/connectable.rb:91:in `ensure_connected'
  mongo (2.2.7) lib/mongo/server/connectable.rb:107:in `read'
  mongo (2.2.7) lib/mongo/server/connection.rb:159:in `deliver'
  mongo (2.2.7) lib/mongo/server/connection.rb:105:in `block in dispatch'
  mongo (2.2.7) lib/mongo/monitoring/publishable.rb:47:in `publish_command'
  mongo (2.2.7) lib/mongo/server/connection.rb:104:in `dispatch'
  mongo (2.2.7) lib/mongo/operation/executable.rb:36:in `block in execute'
  mongo (2.2.7) lib/mongo/server/connection_pool.rb:107:in `with_connection'
  mongo (2.2.7) lib/mongo/server/context.rb:63:in `with_connection'
  mongo (2.2.7) lib/mongo/operation/executable.rb:34:in `execute'
  mongo (2.2.7) lib/mongo/collection/view/iterable.rb:80:in `send_initial_query'
  mongo (2.2.7) lib/mongo/collection/view/iterable.rb:41:in `block in each'
  mongo (2.2.7) lib/mongo/retryable.rb:51:in `read_with_retry'
  mongo (2.2.7) lib/mongo/collection/view/iterable.rb:39:in `each'
  mongoid (5.1.3) lib/mongoid/query_cache.rb:207:in `each'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/adapters/mongodb.rb:89:in `map'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/adapters/mongodb.rb:89:in `block in dataset'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/adapters/mongodb/dataset.rb:8:in `initialize'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/adapters/mongodb.rb:88:in `new'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/adapters/mongodb.rb:88:in `dataset'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/adapters/mongodb.rb:16:in `all'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/adapters/mongodb.rb:21:in `query'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/models/repository.rb:56:in `first'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/repositories/page_repository.rb:41:in `by_fullpath'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/services/page_finder_service.rb:12:in `block in find'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/services/concerns/decorator.rb:11:in `decorate'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/services/page_finder_service.rb:11:in `find'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/services/parent_finder_service.rb:14:in `find'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/liquid/tags/extends.rb:17:in `parse_parent_template'
```

Which is followed by this, which also repeats about a thousand times:

```
  locomotivecms-liquid (4.0.0) lib/liquid/tags/extends.rb:30:in `parse'
  locomotivecms-liquid (4.0.0) lib/liquid/tag.rb:10:in `parse'
  locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:27:in `parse'
  locomotivecms-liquid (4.0.0) lib/liquid/document.rb:10:in `parse'
  locomotivecms-liquid (4.0.0) lib/liquid/document.rb:5:in `parse'
  locomotivecms-liquid (4.0.0) lib/liquid/template.rb:124:in `parse'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/liquid/template.rb:24:in `parse'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/services/liquid_parser_service.rb:19:in `_parse'
  locomotivecms_steam (1.1.1) lib/locomotive/steam/liquid/tags/extends.rb:29:in `parse_parent_template'
```

There was active changes happening on the system at the time that this crash appeared (system  crashes every time we start and access it now.)  I suspect that there is likely something in the SEO content that may be causing the issue (which I will investigate.)  

Is there any tool available that will parse the site and look for data that might cause a processing error?

**Comment by justmark** [comment]
I removed the SEO entries from the pages that were being updated, but that hasn't made any difference at all.

**Comment by did** [comment]
hi @justmark, I guess you've got a circular dependency between your layouts/pages. Meaning one of your pages must extend a page which itself extends the initial page. Well, you get the idea :-) Am I right?
