### ISSUE TITLE
Frozen String issue after updating to v3.2.0...

### ISSUE THREAD

**Issue by interhive** [locomotivecms/engine#1197]
I've updated to v3.2.0 from v3.1.1 and I'm encountering the following error when I attempt to visit the backend of Locomotive:

```shell
I, [2017-02-22T22:22:37.798126 #22878]  INFO -- : Processing by Locomotive::SitesController#index as HTML
D, [2017-02-22T22:22:37.875179 #22878] DEBUG -- : MONGODB | 198.199.75.171:27017 | qis_marketing_production.find | STARTED | {"find"=>"locomotive_accounts", "filter"=>{"_id"=>BSON::ObjectId('571a7fd3fef5ef4c0c70771d')}, "limit"=>-1}
D, [2017-02-22T22:22:37.886352 #22878] DEBUG -- : MONGODB | 198.199.75.171:27017 | qis_marketing_production.find | SUCCEEDED | 0.010912297s
D, [2017-02-22T22:22:37.921734 #22878] DEBUG -- : MONGODB | 198.199.75.171:27017 | qis_marketing_production.find | STARTED | {"find"=>"locomotive_accounts", "filter"=>{"_id"=>BSON::ObjectId('571a7fd3fef5ef4c0c70771d')}, "limit"=>-1}
D, [2017-02-22T22:22:37.922463 #22878] DEBUG -- : MONGODB | 198.199.75.171:27017 | qis_marketing_production.find | SUCCEEDED | 0.0005835349999999999s
D, [2017-02-22T22:22:37.936156 #22878] DEBUG -- : MONGODB | 198.199.75.171:27017 | qis_marketing_production.find | STARTED | {"find"=>"locomotive_sites", "filter"=>{"memberships.account_id"=>BSON::ObjectId('571a7fd3fef5ef4c0c70771d')}, "sort"=>{"name"=>1}}
D, [2017-02-22T22:22:37.941920 #22878] DEBUG -- : MONGODB | 198.199.75.171:27017 | qis_marketing_production.find | SUCCEEDED | 0.016827932s
I, [2017-02-22T22:22:39.813247 #22878]  INFO -- :   Rendered /var/deploy/qis_cms/web_head/shared/bundle/ruby/2.3.0/gems/locomotivecms-3.2.0/app/views/locomotive/shared/account/_navigation.html.slim (21.8ms)
I, [2017-02-22T22:22:39.813676 #22878]  INFO -- :   Rendered /var/deploy/qis_cms/web_head/shared/bundle/ruby/2.3.0/gems/locomotivecms-3.2.0/app/views/locomotive/shared/_account_navigation.slim (32.2ms)
I, [2017-02-22T22:22:39.813930 #22878]  INFO -- :   Rendered /var/deploy/qis_cms/web_head/shared/bundle/ruby/2.3.0/gems/locomotivecms-3.2.0/app/views/locomotive/sites/index.html.slim within locomotive/layouts/account (1811.0ms)
I, [2017-02-22T22:22:39.814446 #22878]  INFO -- : [LocomotiveCMS] [ApplicationError] #<RuntimeError: can't modify frozen String>
I, [2017-02-22T22:22:39.814827 #22878]  INFO -- : Completed 500 Internal Server Error in 2016ms
F, [2017-02-22T22:22:39.825130 #22878] FATAL -- :
RuntimeError (can't modify frozen String):
  locomotivecms (3.2.0) lib/locomotive/dragonfly.rb:55:in `strip!'
  locomotivecms (3.2.0) lib/locomotive/dragonfly.rb:55:in `clean_source!'
  locomotivecms (3.2.0) lib/locomotive/dragonfly.rb:28:in `fetch_file'
  locomotivecms (3.2.0) lib/locomotive/dragonfly.rb:5:in `resize_url'
  locomotivecms (3.2.0) app/helpers/locomotive/shared/accounts_helper.rb:7:in `account_avatar_url'
  locomotivecms (3.2.0) app/views/locomotive/shared/account/_navigation.html.slim:4:in `block in __var_deploy_qis_cms_web_head_shared_bundle_ruby_______gems_locomotivecms_______app_views_locomotive_shared_account__navigation_html_slim___4259308620956367791_69896589337820'
```

Can anyone point me in the right direction to track down why this is happening all of a sudden?

I'm going to revert to v3.1.1 in the meantime.

Thanks!

EDIT: I guess I should mention that I'm running Rails 4.2.8 under Ruby v2.3.3.

**Comment by did** [comment]
hi @interhive, no idea how it happened. I tried with Rails 4.2.8 / Ruby v2.3.3 and I couldn't reproduce it. Perhaps you installed additional gems which modified the behaviour of Carrierwave. 
Anyway the `clean_source!` method was dirty so I updated it. It should fix your issue.
