### ISSUE TITLE
Deploy fails since update

### ISSUE THREAD

**Issue by DonKoko** [locomotivecms/engine#1207]
Since I updated my engine to `3.3.0.rc2` when trying to deploy some old sites I get the following error:
When I rename the file , the deploy goes through but I guess there is something going wrong.
```
  persisting javascripts/app.js [failed]
    Resource invalid: source New file does not have the original extension

# Error description:
Resource invalid: source New file does not have the original extension

# Backtrace:

	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_coal-1.4.0/lib/locomotive/coal/resources/concerns/request.rb:36:in `do_request'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_coal-1.4.0/lib/locomotive/coal/resources/concerns/request.rb:15:in `put'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_coal-1.4.0/lib/locomotive/coal/resources/base.rb:30:in `update'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_sub_commands/push_theme_assets_command.rb:27:in `persist'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:34:in `block in _push'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `each'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `_push'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:25:in `block in _push_with_timezone'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:24:in `_push_with_timezone'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:18:in `block in push'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:50:in `instrument'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:16:in `push'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:12:in `push'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_command.rb:55:in `block in _push'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_command.rb:84:in `block in each_resource'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_command.rb:77:in `each'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_command.rb:77:in `each_resource'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_command.rb:54:in `_push'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_command.rb:41:in `push'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/commands/push_command.rb:31:in `push'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon.rb:73:in `push'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/cli.rb:318:in `deploy'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/bin/wagon:12:in `<top (required)>'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/bin/wagon:22:in `load'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/bin/wagon:22:in `<main>'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	/Users/Donkoko/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by did** [comment]
hi @DonKoko, this has been fixed. Whole story here: https://github.com/locomotivecms/engine/issues/1200.
Sorry about that :-(
