### ISSUE TITLE
Locomotive Back-office error

### ISSUE THREAD

**Issue by lcx** [locomotivecms/engine#1208]
I successfully deployed a site today several times. The site already existed but I just updated several things. 
Since it was a demo page I decided to destroy it and recreate. Once I deployed I again got the error Resource not found that started yesterday and which goes away after some minutes (still need to look into that)

```
Pushing Pages
  persisting index (ro, de) [failed]
    Resource not found

# Error description:
Resource not found
```

But this time after some minutes I got a new error from wagon

```
Pushing Pages
  persisting index (ro, de) [failed]
    Locomotive Back-office error. Contact your administrator or check your application logs.

# Error description:
undefined method `bson_type' for #<File:/tmp/RackMultipart20170411-31927-g5j4xa.jpg>
```
and on the Server: 

```
I, [2017-04-11T07:52:21.619560 #31927]  INFO -- : Started PUT "/locomotive/api/v3/pages/58ec6d55cee13b7cb7a55e22.json" for 146.255.58.228 at 2017-04-11 07:52:21 +0200
I, [2017-04-11T07:52:21.619887 #31927]  INFO -- : [LocomotiveCMS] [fetch site] host = cms.lcx.at / site_handle = "roua-test" / locale = :de
E, [2017-04-11T07:52:21.878019 #31927] ERROR -- : [API] undefined method `bson_type' for #<File:/tmp/RackMultipart20170411-31927-g5j4xa.jpg>
        /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:44:in `block in to_bson'
        /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `each'
        /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `to_bson'
        /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:46:in `block in to_bson'
        /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `each'
        /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `to_bson'
        /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:46:in `block in to_bson'
        /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `each'
        /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `to_bson'
        /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:46:in `block in to_bson'
        /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `each'
        /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `to_bson'
```

I'm running engine from master (commit from yesterday) and wagon 2.3.0.rc1

**Comment by lcx** [comment]
sorry, here is the full backtrace

```
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:44:in `block in to_bson'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `each'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `to_bson'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:46:in `block in to_bson'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `each'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `to_bson'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:46:in `block in to_bson'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `each'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `to_bson'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:46:in `block in to_bson'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `each'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `to_bson'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:46:in `block in to_bson'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `each'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `to_bson'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/array.rb:49:in `block in to_bson'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/array.rb:46:in `each'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/array.rb:46:in `each_with_index'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/array.rb:46:in `to_bson'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:46:in `block in to_bson'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `each'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/hash.rb:43:in `to_bson'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/protocol/serializers.rb:163:in `serialize'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/protocol/message.rb:213:in `block in serialize_fields'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/protocol/message.rb:201:in `each'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/protocol/message.rb:201:in `serialize_fields'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/protocol/message.rb:104:in `serialize'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/connection.rb:193:in `block in write'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/connection.rb:192:in `each'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/connection.rb:192:in `write'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/connection.rb:162:in `deliver'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/connection.rb:108:in `block in dispatch'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/monitoring/publishable.rb:47:in `publish_command'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/connection.rb:107:in `dispatch'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/operation/write/command/writable.rb:39:in `block in execute'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server/connection_pool.rb:107:in `with_connection'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/server.rb:242:in `with_connection'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/operation/write/command/writable.rb:38:in `execute'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/operation/write/write_command_enabled.rb:57:in `execute_write_command'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/operation/write/write_command_enabled.rb:41:in `execute'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/collection/view/writable.rb:242:in `block in update'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/retryable.rb:112:in `write_with_retry'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/collection/view/writable.rb:235:in `update'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongo-2.4.1/lib/mongo/collection/view/writable.rb:209:in `update_one'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/query_cache.rb:182:in `update_one_with_clear_cache'
/var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/persistable/updatable.rb:144:in `block in update_document'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/persistable/updatable.rb:118:in `block (2 levels) in prepare_update'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_update_callbacks'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/interceptable.rb:138:in `run_callbacks'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/persistable/updatable.rb:117:in `block in prepare_update'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/interceptable.rb:138:in `run_callbacks'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/persistable/updatable.rb:116:in `prepare_update'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/persistable/updatable.rb:139:in `update_document'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/persistable/savable.rb:25:in `save'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/mongoid-5.2.1/lib/mongoid/persistable/savable.rb:44:in `save!'
 /var/rails/lcxcms/shared/vendor/bundle/ruby/2.3.0/bundler/gems/engine-cd543dd767e8/app/api/locomotive/api/helpers/persistence_helper.rb:57:in `persist_from_form'
 /var/rails/lcxcms/shared/vendor/bundle/ruby/2.3.0/bundler/gems/engine-cd543dd767e8/app/api/locomotive/api/resources/page_resource.rb:108:in `block (2 levels) in <class:PageResource>'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/grape-0.12.0/lib/grape/endpoint.rb:47:in `call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/grape-0.12.0/lib/grape/endpoint.rb:47:in `block in generate_api_method'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/grape-0.12.0/lib/grape/endpoint.rb:247:in `run'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/grape-0.12.0/lib/grape/endpoint.rb:195:in `block in call!'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/grape-0.12.0/lib/grape/middleware/base.rb:24:in `call!'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/grape-0.12.0/lib/grape/middleware/base.rb:18:in `call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/grape-0.12.0/lib/grape/middleware/error.rb:27:in `block in call!'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/grape-0.12.0/lib/grape/middleware/error.rb:26:in `catch'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/grape-0.12.0/lib/grape/middleware/error.rb:26:in `call!'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/grape-0.12.0/lib/grape/middleware/base.rb:18:in `call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:153:in `call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/grape-0.12.0/lib/grape/endpoint.rb:196:in `call!'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/grape-0.12.0/lib/grape/endpoint.rb:184:in `call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:68:in `optimized_each'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/grape-0.12.0/lib/grape/api.rb:98:in `call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/grape-0.12.0/lib/grape/api.rb:33:in `call!'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/grape-0.12.0/lib/grape/api.rb:29:in `call'
  /var/rails/lcxcms/shared/vendor/bundle/ruby/2.3.0/bundler/gems/engine-cd543dd767e8/app/api/locomotive/api/middlewares/params_decoder_middleware.rb:19:in `call'
  /var/rails/lcxcms/shared/vendor/bundle/ruby/2.3.0/bundler/gems/engine-cd543dd767e8/app/api/locomotive/api/middlewares/logger_middleware.rb:12:in `call'
  /var/rails/lcxcms/shared/vendor/bundle/ruby/2.3.0/bundler/gems/engine-cd543dd767e8/app/api/locomotive/api/middlewares/locale_middleware.rb:22:in `block in call'
  /var/rails/lcxcms/shared/vendor/bundle/ruby/2.3.0/gems/custom_fields-2.8.0/lib/custom_fields/extensions/mongoid/fields/i18n.rb:50:in `with_locale'
  /var/rails/lcxcms/shared/vendor/bundle/ruby/2.3.0/bundler/gems/engine-cd543dd767e8/app/api/locomotive/api/middlewares/locale_middleware.rb:21:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:153:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/mapper.rb:51:in `serve'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'
  /var/rails/lcxcms/shared/vendor/bundle/ruby/2.3.0/bundler/gems/engine-cd543dd767e8/lib/locomotive/middlewares/site.rb:26:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/dragonfly-1.1.1/lib/dragonfly/middleware.rb:14:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/etag.rb:24:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/conditionalget.rb:38:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/flash.rb:260:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `block in call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:26:in `tagged'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `tagged'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /var/rails/lcxcms/shared/vendor/bundle/ruby/2.3.0/bundler/gems/engine-cd543dd767e8/lib/locomotive/middlewares/image_thumbnail.rb:23:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/dragonfly-1.1.1/lib/dragonfly/cookie_monster.rb:9:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
  /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
 /var/rails/lcxcms/releases/20170410114838/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by lcx** [comment]
this is not a bug. 
A bit hard to debug but the issue was the site, not locomotive. 
What happened: 
The index.liquid was completely redone and several images where removed unfortunately this wasn't done in the german version (index.de.liquid) 
All Images where still present in editable_elements which caused this issue during deploy.
