### ISSUE TITLE
Filtering using `with_scope` crashes when `entry.attribute` has an empty value

### ISSUE THREAD

**Issue by DonKoko** [locomotivecms/engine#1213]
Currently it seems like using `with_scope` to filter based on attributes which are `required: false` is breaking. 
Here is my example code I am using:
```
{% with_scope municipality._id: "{{params.gemeente}}" %}
  {% for location in activity.locations %}
    {% include 'location_content' %}
  {% endfor %}
{% endwith_scope %}
```

And here is how the `location` relationship with `municipality` looks like:
```
- municipality:
    label: Gemeente
    hint: "De gemeente waar de locatie zich bevindt."
    type: belongs_to
    class_name: municipalities
    ui_enabled: true
    requred: false
```

As you can see the field is not required, so when I try to filter using the code shown above,  it crashes. I don't know enough on how loco works to figure it out myself, but I guess the reason for the error is that the filtering for non-required relationships is missing something.

Hope this is helpful. 
Here is also the full trace:
```
undefined method `[]' for nil:NilClass

No code

BACKTRACE

/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-solid-4.0.1/lib/solid/parser/ripper.rb:22:in `dive_in'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-solid-4.0.1/lib/solid/parser/ripper.rb:14:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-solid-4.0.1/lib/solid/parser/ripper.rb:4:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-solid-4.0.1/lib/solid/parser.rb:103:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-solid-4.0.1/lib/solid/arguments.rb:15:in `parse!'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-solid-4.0.1/lib/solid/arguments.rb:5:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-solid-4.0.1/lib/solid/element.rb:10:in `initialize'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/liquid/tags/with_scope.rb:36:in `initialize'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/tag.rb:9:in `new'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/tag.rb:9:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:27:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:63:in `parse_body'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/if.rb:24:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/tag.rb:10:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:27:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:63:in `parse_body'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/if.rb:24:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/tag.rb:10:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:27:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:63:in `parse_body'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:10:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/inherited_block.rb:55:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/liquid/tags/inherited_block.rb:28:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/tag.rb:10:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:27:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/extends.rb:45:in `parse_body'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:10:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/extends.rb:28:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/tag.rb:10:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:27:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/document.rb:10:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/document.rb:5:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:124:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/liquid/template.rb:24:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/services/liquid_parser_service.rb:26:in `_parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/services/liquid_parser_service.rb:9:in `parse'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/renderer.rb:39:in `parse_and_render_liquid'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/renderer.rb:22:in `render_page'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/renderer.rb:10:in `_call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/path.rb:13:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/redirection.rb:15:in `_call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/locale.rb:24:in `block in _call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/i18n-0.8.1/lib/i18n.rb:257:in `with_locale'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/locale.rb:23:in `_call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/timezone.rb:16:in `block in _call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/timezone.rb:15:in `_call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/robots.rb:15:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/logging.rb:18:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/default_env.rb:15:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/lint.rb:49:in `_call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/lint.rb:37:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_wagon-2.3.0.rc1/lib/locomotive/wagon/middlewares/error_page.rb:16:in `_call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/rack-livereload-0.3.16/lib/rack/livereload.rb:23:in `_call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/rack-livereload-0.3.16/lib/rack/livereload.rb:14:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/dragonfly-1.1.1/lib/dragonfly/middleware.rb:14:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/dynamic_assets.rb:22:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/static.rb:149:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/locomotivecms_steam-1.3.0.rc1/lib/locomotive/steam/middlewares/favicon.rb:15:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:153:in `call'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/thin-1.7.0/lib/thin/connection.rb:50:in `block in process'
/Users/Donkoko/.rvm/gems/ruby-2.3.1/gems/eventmachine-1.2.3/lib/eventmachine.rb:1076:in `block in spawn_threadpool'

I have a similar example that I think doesn't work because of the same reason. Let me know if I should share it here.

**Comment by did** [comment]
hmmm, I close it because of this line ```{% with_scope municipality._id: "{{params.gemeente}}" %}``` which is not valid (should be ```{% with_scope municipality._id: params.gemeente %}```)

**Comment by DonKoko** [comment]
Yep, my mistake. Thanks for pointing out.
