### ISSUE TITLE
Issues attempting new install

### ISSUE THREAD

**Issue by Sja91** [locomotivecms/engine#1249]
I'm receiving the following output when I try to run a new install of Locomotive:

```
I, [2018-08-31T23:21:25.702453 #13064]  INFO -- : listening on addr=0.0.0.0:8080 fd=9
I, [2018-08-31T23:21:25.702844 #13064]  INFO -- : worker=0 spawning...
I, [2018-08-31T23:21:25.703664 #13064]  INFO -- : master process ready
I, [2018-08-31T23:21:25.704435 #13067]  INFO -- : worker=0 spawned pid=13067
I, [2018-08-31T23:21:25.704728 #13067]  INFO -- : Refreshing Gem list
/var/lib/gems/2.3.0/gems/activesupport-3.2.19/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
/var/lib/gems/2.3.0/gems/locomotive_liquid-2.4.2/lib/liquid/htmltags.rb:43: warning: key "index0" is duplicated and overwritten on line 46
/var/lib/gems/2.3.0/gems/fog-1.12.1/lib/fog/aws/compute.rb:200: warning: key :internet_gateways is duplicated and overwritten on line 208
Digest::Digest is deprecated; use Digest
/var/lib/gems/2.3.0/gems/fog-1.12.1/lib/fog/rackspace/mock_data.rb:41: warning: key "name" is duplicated and overwritten on line 79
E, [2018-08-31T23:21:28.034420 #13067] ERROR -- : undefined method `secret_key=' for Devise:Module
Did you mean?  request_keys= (NoMethodError)
/usr/local/loco_app/loco_serv/config/initializers/devise.rb:4:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/devise-2.2.7/lib/devise.rb:267:in `setup'
/usr/local/loco_app/loco_serv/config/initializers/devise.rb:3:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/2.3.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/2.3.0/gems/railties-3.2.19/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.3.0/gems/railties-3.2.19/lib/rails/engine.rb:592:in `each'
/var/lib/gems/2.3.0/gems/railties-3.2.19/lib/rails/engine.rb:592:in `block in <class:Engine>'
/var/lib/gems/2.3.0/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.3.0/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.3.0/gems/railties-3.2.19/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/2.3.0/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `each'
/var/lib/gems/2.3.0/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.3.0/gems/railties-3.2.19/lib/rails/application.rb:136:in `initialize!'
/var/lib/gems/2.3.0/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
/usr/local/loco_app/loco_serv/config/environment.rb:5:in `<top (required)>'
config.ru:4:in `require'
config.ru:4:in `block in <main>'
/var/lib/gems/2.3.0/gems/rack-1.4.7/lib/rack/builder.rb:51:in `instance_eval'
/var/lib/gems/2.3.0/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/var/lib/gems/2.3.0/gems/unicorn-5.4.1/lib/unicorn.rb:56:in `eval'
/var/lib/gems/2.3.0/gems/unicorn-5.4.1/lib/unicorn.rb:56:in `block in builder'
/var/lib/gems/2.3.0/gems/unicorn-5.4.1/bin/unicorn_rails:139:in `block in rails_builder'
/var/lib/gems/2.3.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:795:in `build_app!'
/var/lib/gems/2.3.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:660:in `init_worker_process'
/var/lib/gems/2.3.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:682:in `worker_loop'
/var/lib/gems/2.3.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
/var/lib/gems/2.3.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:142:in `start'
/var/lib/gems/2.3.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
/usr/local/bin/unicorn_rails:23:in `load'
/usr/local/bin/unicorn_rails:23:in `<main>'
E, [2018-08-31T23:21:28.050500 #13064] ERROR -- : reaped #<Process::Status: pid 13067 exit 1> worker=0
```

And then it just repeats non-stop, and I can't reach the server.

**Comment by did** [comment]
It looks like an error in the Devise configuration 

```E, [2018-08-31T23:21:28.034420 #13067] ERROR -- : undefined method `secret_key=' for Devise:Module```
