### ISSUE TITLE
Forgot password form gives undefined method 'bson_type' for Locomotive::Steam::ContentEntryRepository

### ISSUE THREAD

**Issue by fabioskap** [locomotivecms/engine#1331]
Hi @did,

**Wagon version**: 2.3.1
**Locomotive version**: 3.4.0
**Mongo version**: 3.4-jessie (and I also try with 3.4.7)

I used the Authentication feature to build private access sections and it worked fine until I restore the site. After restore, the _reset password action_ doesn't work and in the log there is this error:

```
F, [2019-06-21T09:46:45.690683 #770] FATAL -- : [01191b75-c725-4176-81cd-681d6b100286]
   
F, [2019-06-21T09:46:45.728144 #770] FATAL -- : [01191b75-c725-4176-81cd-681d6b100286] NoMethodError (undefined method 'bson_type' for #<Locomotive::Steam::ContentEntryRepository:0x000055ec2f943010>):

F, [2019-06-21T09:46:45.728232 #770] FATAL -- : [01191b75-c725-4176-81cd-681d6b100286]
   
F, [2019-06-21T09:46:45.728281 #770] FATAL -- : [01191b75-c725-4176-81cd-681d6b100286] activesupport (5.1.7) lib/active_support/core_ext/object/try.rb:17:in 'public_send'
```

This is my **site.yml** file:
```yaml
metafields:
 smtp:
    address: "smtp.eu.mailgun.org"
    port: 587
    user_name: "email@domain.com"
    password: "password"
```
And this is my **metafields_schema.yml** file:
```yaml
smtp:
  label: SMTP
  fields:
    address:
      type: string
    port:
      type: integer
    user_name:
      type: string
    password:
      type: string
```
Can you provide some insight?

Thank you

**Comment by did** [comment]
@fabioskap forgot to answer it :-( sorry. Do you still have the full logs of this error?

**Comment by fabioskap** [comment]
> @fabioskap forgot to answer it :-( sorry. Do you still have the full logs of this error?
```
D, [2019-08-05T09:00:19.656412 #4183] DEBUG -- : MONGODB | mongo:27017 | locomotiveapp_production.find | SUCCEEDED | 0.000s
F, [2019-08-05T09:00:19.658732 #4183] FATAL -- :   
F, [2019-08-05T09:00:19.702256 #4183] FATAL -- : NoMethodError (undefined method `bson_type' for #<Locomotive::Steam::ContentEntryRepository:0x0000564c1e3df0c0>):
F, [2019-08-05T09:00:19.702325 #4183] FATAL -- :   
F, [2019-08-05T09:00:19.702397 #4183] FATAL -- : activesupport (5.1.7) lib/active_support/core_ext/object/try.rb:17:in `public_send'
activesupport (5.1.7) lib/active_support/core_ext/object/try.rb:17:in `try!'
activesupport (5.1.7) lib/active_support/core_ext/object/try.rb:6:in `try'
locomotivecms_steam (1.4.1) lib/locomotive/steam/models/associations/referenced.rb:50:in `method_missing'
bson (4.4.2) lib/bson/hash.rb:42:in `put_hash'
bson (4.4.2) lib/bson/hash.rb:42:in `to_bson'
mongo (2.8.0) lib/mongo/protocol/serializers.rb:326:in `serialize'
mongo (2.8.0) lib/mongo/protocol/message.rb:237:in `block in serialize_fields'
mongo (2.8.0) lib/mongo/protocol/message.rb:225:in `each'
mongo (2.8.0) lib/mongo/protocol/message.rb:225:in `serialize_fields'
mongo (2.8.0) lib/mongo/protocol/message.rb:126:in `serialize'
mongo (2.8.0) lib/mongo/server/connection_base.rb:123:in `serialize'
mongo (2.8.0) lib/mongo/server/connection_base.rb:96:in `deliver'
mongo (2.8.0) lib/mongo/server/connection.rb:299:in `deliver'
mongo (2.8.0) lib/mongo/server/connection_base.rb:90:in `dispatch'
mongo (2.8.0) lib/mongo/operation/shared/executable.rb:42:in `block in dispatch_message'
mongo (2.8.0) lib/mongo/server/connection_pool.rb:123:in `with_connection'
mongo (2.8.0) lib/mongo/server.rb:334:in `with_connection'
mongo (2.8.0) lib/mongo/operation/shared/executable.rb:41:in `dispatch_message'
mongo (2.8.0) lib/mongo/operation/shared/executable.rb:36:in `get_result'
mongo (2.8.0) lib/mongo/operation/shared/executable_no_validate.rb:25:in `execute'
mongo (2.8.0) lib/mongo/operation/shared/write.rb:40:in `execute'
mongo (2.8.0) lib/mongo/collection/view/writable.rb:307:in `block (2 levels) in update_one'
mongo (2.8.0) lib/mongo/retryable.rb:203:in `legacy_write_with_retry'
mongo (2.8.0) lib/mongo/retryable.rb:132:in `write_with_retry'
mongo (2.8.0) lib/mongo/collection/view/writable.rb:295:in `block in update_one'
mongo (2.8.0) lib/mongo/cluster.rb:651:in `with_session'
mongo (2.8.0) lib/mongo/client.rb:663:in `with_session'
mongo (2.8.0) lib/mongo/collection/view.rb:204:in `with_session'
mongo (2.8.0) lib/mongo/collection/view/writable.rb:294:in `update_one'
mongoid (6.4.2) lib/mongoid/query_cache.rb:182:in `update_one_with_clear_cache'
locomotivecms_steam (1.4.1) lib/locomotive/steam/adapters/mongodb/command.rb:26:in `block in update'
locomotivecms_steam (1.4.1) lib/locomotive/steam/adapters/mongodb/command.rb:24:in `tap'
locomotivecms_steam (1.4.1) lib/locomotive/steam/adapters/mongodb/command.rb:24:in `update'
locomotivecms_steam (1.4.1) lib/locomotive/steam/adapters/mongodb.rb:39:in `update'
locomotivecms_steam (1.4.1) lib/locomotive/steam/models/repository.rb:36:in `update'
locomotivecms_steam (1.4.1) lib/locomotive/steam/services/content_entry_service.rb:68:in `block in update_decorated_entry'
locomotivecms_steam (1.4.1) lib/locomotive/steam/services/content_entry_service.rb:108:in `with_repository'
locomotivecms_steam (1.4.1) lib/locomotive/steam/services/content_entry_service.rb:63:in `update_decorated_entry'
/usr/local/lib/ruby/2.5.0/delegate.rb:83:in `method_missing'
locomotivecms_steam (1.4.1) lib/locomotive/steam/services/auth_service.rb:60:in `forgot_password'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/auth.rb:71:in `forgot_password'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/auth.rb:25:in `_call'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/thread_safe.rb:12:in `call'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/redirection.rb:15:in `_call'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/thread_safe.rb:12:in `call'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/thread_safe.rb:14:in `call'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/locale.rb:24:in `block in _call'
i18n (1.6.0) lib/i18n.rb:297:in `with_locale'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/locale.rb:23:in `_call'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/thread_safe.rb:12:in `call'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/thread_safe.rb:14:in `call'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/timezone.rb:16:in `block in _call'
activesupport (5.1.7) lib/active_support/core_ext/time/zones.rb:64:in `use_zone'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/timezone.rb:15:in `_call'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/thread_safe.rb:12:in `call'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/robots.rb:15:in `call'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/thread_safe.rb:14:in `call'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/logging.rb:18:in `call'
locomotivecms (3.4.1) lib/locomotive/steam/middlewares/catch_error.rb:13:in `call'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/thread_safe.rb:19:in `next'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/thread_safe.rb:14:in `call'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/default_env.rb:15:in `call'
dragonfly (1.1.5) lib/dragonfly/middleware.rb:14:in `call'
locomotivecms_steam (1.4.1) lib/locomotive/steam/middlewares/favicon.rb:15:in `call'
rack-rewrite (1.5.1) lib/rack/rewrite.rb:24:in `call'
rack (2.0.7) lib/rack/builder.rb:153:in `call'
actionpack (5.1.7) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.1.7) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.1.7) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.7) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.7) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.7) lib/action_dispatch/routing/route_set.rb:844:in `call'
locomotivecms (3.4.1) lib/locomotive/middlewares/site.rb:26:in `call'
dragonfly (1.1.5) lib/dragonfly/middleware.rb:14:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.7) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.7) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
locomotivecms (3.4.1) lib/locomotive/middlewares/image_thumbnail.rb:23:in `call'
dragonfly (1.1.5) lib/dragonfly/cookie_monster.rb:9:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
passenger (6.0.1) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
passenger (6.0.1) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
passenger (6.0.1) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
passenger (6.0.1) src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
passenger (6.0.1) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

```

**Comment by asabaini** [comment]
hey @did, did you manage to take a look at this issue by any chance?

**Comment by did** [comment]
@asabaini do you still have the issue? Have you tried with Engine v4?

**Comment by asabaini** [comment]
@did yes, I have a couple of websites with 3.4.1. I was testing v4 the other day but I am having issues with `wagon clone` and `wagon deploy` and I am still figuring out what went wrong. Here is the log from the v4 wagon deploy for context, I know that it does not relate to the issue at hand

```bash
bundle exec wagon deploy production -v

# Error description:
error

# Backtrace:

	/usr/local/bundle/gems/locomotivecms_coal-1.6.0/lib/locomotive/coal/resources/concerns/request.rb:54:in `do_request'
	/usr/local/bundle/gems/locomotivecms_coal-1.6.0/lib/locomotive/coal/resources/concerns/request.rb:11:in `post'
	/usr/local/bundle/gems/locomotivecms_coal-1.6.0/lib/locomotive/coal/resources/token.rb:9:in `get'
	/usr/local/bundle/gems/locomotivecms_coal-1.6.0/lib/locomotive/coal/client.rb:17:in `token'
	/usr/local/bundle/gems/locomotivecms_coal-1.6.0/lib/locomotive/coal/client.rb:100:in `block in connection'
	/usr/local/bundle/gems/locomotivecms_coal-1.6.0/lib/locomotive/coal/resources/concerns/request.rb:111:in `_token'
	/usr/local/bundle/gems/locomotivecms_coal-1.6.0/lib/locomotive/coal/resources/concerns/request.rb:69:in `_do_request'
	/usr/local/bundle/gems/locomotivecms_coal-1.6.0/lib/locomotive/coal/resources/concerns/request.rb:27:in `do_request'
	/usr/local/bundle/gems/locomotivecms_coal-1.6.0/lib/locomotive/coal/resources/concerns/request.rb:7:in `get'
	/usr/local/bundle/gems/locomotivecms_coal-1.6.0/lib/locomotive/coal/resources/current_site.rb:9:in `get'
	/usr/local/bundle/gems/locomotivecms_wagon-3.0.3/lib/locomotive/wagon/commands/push_command.rb:173:in `remote_site'
	/usr/local/bundle/gems/locomotivecms_wagon-3.0.3/lib/locomotive/wagon/commands/push_command.rb:77:in `validate!'
	/usr/local/bundle/gems/locomotivecms_wagon-3.0.3/lib/locomotive/wagon/commands/push_command.rb:60:in `_push'
	/usr/local/bundle/gems/locomotivecms_wagon-3.0.3/lib/locomotive/wagon/commands/push_command.rb:51:in `push'
	/usr/local/bundle/gems/locomotivecms_wagon-3.0.3/lib/locomotive/wagon/commands/push_command.rb:31:in `push'
	/usr/local/bundle/gems/locomotivecms_wagon-3.0.3/lib/locomotive/wagon.rb:74:in `push'
	/usr/local/bundle/gems/locomotivecms_wagon-3.0.3/lib/locomotive/wagon/cli.rb:352:in `deploy'
	/usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	/usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	/usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	/usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	/usr/local/bundle/gems/locomotivecms_wagon-3.0.3/bin/wagon:73:in `<top (required)>'
	/usr/local/bundle/bin/wagon:23:in `load'
	/usr/local/bundle/bin/wagon:23:in `<top (required)>'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
	/usr/local/bundle/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	/usr/local/bundle/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
	/usr/local/bundle/bin/bundle:23:in `load'
	/usr/local/bundle/bin/bundle:23:in `<main>'
```

**Comment by did** [comment]
@asabaini what are your engine logs? It looks like Engine returned an application error when you tried to deploy your site.

**Comment by asabaini** [comment]
@did this are the engine logs after a `wagon clone`. Fresh new locomotive site created from the web UI. I tried `wagon init` and `wagon deploy` but the error and logs are the same

```bash
Started POST "/locomotive/api/v3/tokens.json" for 127.0.0.1 at 2020-01-22 08:50:39 +0100
MONGODB | mongo:27017 | locomotiveapp_development.find | STARTED | {"find"=>"locomotive_accounts", "filter"=>{"api_key"=>"5b60a0f060133d3372cf5a1635b5e08a32dba3cd"}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true}
MONGODB | mongo:27017 | locomotiveapp_development.find | SUCCEEDED | 0.001s

NoMethodError (undefined method `[]' for nil:NilClass):

grape (1.1.0) lib/grape/router.rb:163:in `cascade?'
grape (1.1.0) lib/grape/router.rb:95:in `transaction'
grape (1.1.0) lib/grape/router.rb:72:in `identity'
grape (1.1.0) lib/grape/router.rb:57:in `block in call'
grape (1.1.0) lib/grape/router.rb:137:in `with_optimization'
grape (1.1.0) lib/grape/router.rb:56:in `call'
grape (1.1.0) lib/grape/api.rb:119:in `call'
grape (1.1.0) lib/grape/api.rb:45:in `call!'
grape (1.1.0) lib/grape/api.rb:40:in `call'
locomotivecms (4.0.1) app/api/locomotive/api/middlewares/params_decoder_middleware.rb:19:in `call'
locomotivecms (4.0.1) app/api/locomotive/api/middlewares/logger_middleware.rb:12:in `call'
locomotivecms (4.0.1) app/api/locomotive/api/middlewares/locale_middleware.rb:22:in `block in call'
custom_fields (2.10.0) lib/custom_fields/extensions/mongoid/fields/i18n.rb:50:in `with_locale'
locomotivecms (4.0.1) app/api/locomotive/api/middlewares/locale_middleware.rb:21:in `call'
rack (2.1.1) lib/rack/builder.rb:176:in `call'
actionpack (5.2.4.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (5.2.4.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
locomotivecms (4.0.1) lib/locomotive/middlewares/site.rb:26:in `call'
dragonfly (1.2.0) lib/dragonfly/middleware.rb:14:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.1.1) lib/rack/tempfile_reaper.rb:17:in `call'
rack (2.1.1) lib/rack/etag.rb:27:in `call'
rack (2.1.1) lib/rack/conditional_get.rb:40:in `call'
rack (2.1.1) lib/rack/head.rb:14:in `call'
actionpack (5.2.4.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.1.1) lib/rack/session/abstract/id.rb:277:in `context'
rack (2.1.1) lib/rack/session/abstract/id.rb:271:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.4.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.1.1) lib/rack/method_override.rb:24:in `call'
rack (2.1.1) lib/rack/runtime.rb:24:in `call'
activesupport (5.2.4.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
locomotivecms (4.0.1) lib/locomotive/middlewares/image_thumbnail.rb:23:in `call'
dragonfly (1.2.0) lib/dragonfly/cookie_monster.rb:9:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.1.1) lib/rack/sendfile.rb:113:in `call'
railties (5.2.4.1) lib/rails/engine.rb:524:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by superturbo** [comment]
@asabaini try downgrade rack to 2.0.8

**Comment by asabaini** [comment]
@superturbo that did the trick thanks

**Comment by asabaini** [comment]
@did I managed to deploy a new site on v4 and the forgot password issue posted by @fabioskap is still there. I think I found the root cause: `accounts.yml` is in a `has_many` relationship with another model called `pharmacists.yml`, created according to the documentation <https://doc.locomotivecms.com/v3.4/docs/relate-two-content-types>

```yaml
# accounts.yml
- pharmacists:
    label: Farmacisti
    type: has_many
    class_name: pharmacists
    inverse_of: account
    ui_enabled: true
```

```yaml
# pharmacists.yml

- account:
    label: Accounts
    type: belongs_to
    class_name: accounts
    required: false
```

By removing the entire `pharmacists` section from `accounts.yml` the forgot password functionality works again. I think I could have guessed it from the original log posted by @fabioskap 
```bash
locomotivecms_steam (1.4.1) lib/locomotive/steam/models/associations/referenced.rb:50:in `method_missing'
```

Is there a problem with my `has_many`? I can't point out what went wrong with it?

**Comment by did** [comment]
> @asabaini try downgrade rack to 2.0.8

I don't understand why I don't get this error when I run the specs..

**Comment by did** [comment]
@asabaini now that you've got Engine 4 up and running, could you try to deploy with the last version of Wagon and see if it solves your has_many relationship issue?

**Comment by asabaini** [comment]
@did I tried on both 3.4.1 and 4. The has_many issue is still present; logs are the same as the one posted by the OP <https://github.com/locomotivecms/engine/issues/1331#issuecomment-518112294>
