### ISSUE TITLE
Engine V4.0.0 installation failure (locomotive:install generator bug)

### ISSUE THREAD

**Issue by clecoufl** [locomotivecms/engine#1359]
## TESTED ENVIRONMENT(S): all producing same error

All environments include nodejs & imagemagick

**Test 1 : DOCKER : ALPINE ruby 2.6.5 and rails 5.2.4**
OS : Alpine Linux 3.10 (Docker)
ruby -v : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]
rails -v : Rails 5.2.4

**Test 2 : DOCKER : ALPINE ruby 2.5.5 and rails 5.2.4**
OS : Alpine Linux 3.9 (Docker)
ruby -v : ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-musl]
rails -v : Rails 5.2.4

**Test 3 : DOCKER : DEBIAN ruby 2.6.5 and rails 5.2.4**
OS : Debian buster (Docker)
ruby -v : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
rails -v : Rails 5.2.4

**Test 4 : OSX : ruby 2.6.5 and rails 5.2.4**
OS : Mac OSX (mojave 10.14.6)
ruby -v : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
rails -v : Rails 5.2.4

## PROCEDURE FOLLOWED :

Followed provided instructions for locomotive v4 install : [getting-started-with-locomotive](https://doc.locomotivecms.com/docs/getting-started-with-locomotive)

```bash
rails new locomotiveapp --skip-bundle --skip-active-record
cd locomotivepp
rm public/robots.txt

# Add devise and mongoid gems to Gemfile >>
gem 'devise', '~> 4.7.1'
gem 'mongoid', '~> 6.4.0'

bundle install
rails generate mongoid:config
rails generate devise:install

# Add Locomotive CMS gem to Gemfile >>
gem 'locomotivecms', '~> 4.0.0'

bundle update

# Next command fails : 
bundle exec rails generate locomotive:install
```

## ERROR : 

```
/usr/local/bundle/gems/locomotivecms-4.0.0/lib/generators/locomotive/install/install_generator.rb:37: warning: else without rescue is useless
[WARNING] Could not load generator "generators/locomotive/install/install_generator". Error: /usr/local/bundle/gems/locomotivecms-4.0.0/lib/generators/locomotive/install/install_generator.rb:102: syntax error, unexpected end-of-input, expecting keyword_end.
/usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/command/behavior.rb:84:in `block (2 levels) in lookup'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/command/behavior.rb:80:in `each'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/command/behavior.rb:80:in `block in lookup'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/command/behavior.rb:79:in `each'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/command/behavior.rb:79:in `lookup'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/generators.rb:257:in `find_by_namespace'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/generators.rb:274:in `invoke'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/commands/generate/generate_command.rb:26:in `perform'
/usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/command/base.rb:69:in `perform'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/command.rb:46:in `invoke'
/usr/local/bundle/gems/railties-5.2.4/lib/rails/commands.rb:18:in `<top (required)>'
/usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
/usr/local/bundle/gems/locomotivecms-4.0.0/lib/generators/locomotive/install/install_generator.rb:37: warning: else without rescue is useless
Could not find generator 'locomotive:install'. Maybe you meant 'devise:install', 'pundit:install' or 'responders:install'
Run `rails generate --help` for more options.
```

## NOTES:

**1) Master branch**
I also tried with latest master which resulted in the same error.
gem 'locomotivecms', git: 'https://github.com/locomotivecms/engine.git', branch: 'master'

**2) Install procedure**

Is there a reason for installing and generating devise and mongoid before installing and generating locomotive install ?
I found that doing the following procedure (for engine 3.4.1) works fine (without re-fetching new versions of certain gems in the process)

```
rails new locomotiveapp --skip-bundle --skip-active-record
cd locomotivepp
rm public/robots.txt

# NB : Not adding devise and mongoid to Gemfile
# Add Locomotive CMS gem to Gemfile >>
gem 'locomotivecms', '~> 4.0.0'

bundle install
rails generate mongoid:config
rails generate devise:install

bundle update
bundle exec rails generate locomotive:install
bundle install
```

I would also amend the current procedure to prepare engine for production with :

==> START : export RAILS_ENV=development

==> Replace bundle exec rails generate locomotive:install command by : 

```
APP_SECRET=$(bundle exec rake secret)
echo "SECRET_KEY_BASE=\"${APP_SECRET}\"" >> .env
source .env
SECRET_KEY_BASE=${SECRET_KEY_BASE} bundle exec rails generate locomotive:install
bundle install

# Precompile assets
RAILS_ENV=production SECRET_KEY_BASE=${SECRET_KEY_BASE} bundle exec rake assets:precompile
```

**Comment by did** [comment]
thanks @clecoufl for the very precise bug description.
About mongo and devise, if they're not installed at first, the `generate locomotive:install` command won't work.
