### ISSUE TITLE
grape versions under 1.3.0 are incompattible with rack 2.1.0 and above

### ISSUE THREAD

**Issue by 3limin4t0r** [locomotivecms/engine#1364]
When following the [Install Locomotive Engine][1] guide the engine server craches when trying to execute the following command on the wagon:

``` bash
bundle exec wagon deploy local -d -v
```

The engine shows the following:

``` none
MONGODB | localhost:27017 | locomotiveapp_development.find | SUCCEEDED | 0.001s
  
NoMethodError (undefined method `[]' for nil:NilClass):
  
grape (1.1.0) lib/grape/router.rb:163:in `cascade?'
grape (1.1.0) lib/grape/router.rb:95:in `transaction'
grape (1.1.0) lib/grape/router.rb:72:in `identity'
grape (1.1.0) lib/grape/router.rb:57:in `block in call'
grape (1.1.0) lib/grape/router.rb:137:in `with_optimization'
grape (1.1.0) lib/grape/router.rb:56:in `call'
grape (1.1.0) lib/grape/api.rb:119:in `call'
grape (1.1.0) lib/grape/api.rb:45:in `call!'
grape (1.1.0) lib/grape/api.rb:40:in `call'
locomotivecms (4.0.1) app/api/locomotive/api/middlewares/params_decoder_middleware.rb:19:in `call'
locomotivecms (4.0.1) app/api/locomotive/api/middlewares/logger_middleware.rb:12:in `call'
locomotivecms (4.0.1) app/api/locomotive/api/middlewares/locale_middleware.rb:22:in `block in call'
custom_fields (2.10.0) lib/custom_fields/extensions/mongoid/fields/i18n.rb:50:in `with_locale'
locomotivecms (4.0.1) app/api/locomotive/api/middlewares/locale_middleware.rb:21:in `call'
rack (2.1.2) lib/rack/builder.rb:177:in `call'
actionpack (5.2.4.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (5.2.4.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
locomotivecms (4.0.1) lib/locomotive/middlewares/site.rb:26:in `call'
dragonfly (1.2.0) lib/dragonfly/middleware.rb:14:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.1.2) lib/rack/tempfile_reaper.rb:17:in `call'
rack (2.1.2) lib/rack/etag.rb:27:in `call'
rack (2.1.2) lib/rack/conditional_get.rb:40:in `call'
rack (2.1.2) lib/rack/head.rb:14:in `call'
actionpack (5.2.4.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.1.2) lib/rack/session/abstract/id.rb:269:in `context'
rack (2.1.2) lib/rack/session/abstract/id.rb:263:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.4.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.1.2) lib/rack/method_override.rb:24:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.2.4.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
locomotivecms (4.0.1) lib/locomotive/middlewares/image_thumbnail.rb:23:in `call'
dragonfly (1.2.0) lib/dragonfly/cookie_monster.rb:9:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.2.4.1) lib/rails/engine.rb:524:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

After looking around a bit I found the following issue: https://github.com/ruby-grape/grape/issues/1966

The current gemspec defines:

https://github.com/locomotivecms/engine/blob/dcdd7375cc95112b1e63e1a19d3847437cd230be/locomotivecms.gemspec#L68

Resolving to 1.1.0.

Which is incompatible with rack 2.1.0, defined by actionpack:

From the Gemfile.lock:

``` none
    actionpack (5.2.4.1)
      actionview (= 5.2.4.1)
      activesupport (= 5.2.4.1)
      rack (~> 2.0, >= 2.0.8)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
```

This resolve to the latest v2 rack version, currently 2.1.2.

I currently solved this issue by specifying the following in my Gemfile

``` ruby
# https://github.com/ruby-grape/grape/issues/1966
gem 'rack', '~> 2.0.8'
```

However it would be better to bump the current specified grape version to a minimum of 1.3.0. I'm not sure if this will break anything, but thought it would at least be worth creating an issue for.

[1]: https://doc.locomotivecms.com/docs/getting-started-with-locomotive

**Comment by did** [comment]
thanks @3limin4t0r for the very clear explanation of the bug.
