### ISSUE TITLE
Admin assets error ActionView::Template::Error (Nil location provided. Can't build URI.)

### ISSUE THREAD

**Issue by numito** [locomotivecms/engine#1396]
In the admin I have 2 pages of assets, when I click on the second page I have the following error. 
It seems there is a content that is invalid/incomplete inside Mongo and the engine admin can't render the page. 

```
F, [2022-07-15T13:19:39.758991 #8525] FATAL -- : [20a94cbf-f983-4236-9386-52e02c46da86]   
F, [2022-07-15T13:19:39.759078 #8525] FATAL -- : [20a94cbf-f983-4236-9386-52e02c46da86] ActionView::Template::Error (Nil location provided. Can't build URI.):
F, [2022-07-15T13:19:39.759482 #8525] FATAL -- : [20a94cbf-f983-4236-9386-52e02c46da86]     16:         .body
[20a94cbf-f983-4236-9386-52e02c46da86]     17:           .small-thumbnail
[20a94cbf-f983-4236-9386-52e02c46da86]     18:             - if asset_with_thumbnail?(asset)
[20a94cbf-f983-4236-9386-52e02c46da86]     19:               = image_tag asset.alternative_vignette_url
[20a94cbf-f983-4236-9386-52e02c46da86]     20:             - else
[20a94cbf-f983-4236-9386-52e02c46da86]     21:               div class="not-a-image #{asset.content_type}"
[20a94cbf-f983-4236-9386-52e02c46da86]     22:                 span= asset_text(asset)
F, [2022-07-15T13:19:39.759514 #8525] FATAL -- : [20a94cbf-f983-4236-9386-52e02c46da86]   
F, [2022-07-15T13:19:39.759732 #8525] FATAL -- : [20a94cbf-f983-4236-9386-52e02c46da86] vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.5/lib/action_dispatch/routing/polymorphic_routes.rb:226:in `polymorphic_method'
[20a94cbf-f983-4236-9386-52e02c46da86] vendor/bundle/ruby/2.7.0/gems/actionpack-5.2.4.5/lib/action_dispatch/routing/polymorphic_routes.rb:116:in `polymorphic_url'
[20a94cbf-f983-4236-9386-52e02c46da86] vendor/bundle/ruby/2.7.0/gems/actionview-5.2.4.5/lib/action_view/helpers/asset_tag_helper.rb:477:in `resolve_image_source'
[20a94cbf-f983-4236-9386-52e02c46da86] vendor/bundle/ruby/2.7.0/gems/actionview-5.2.4.5/lib/action_view/helpers/asset_tag_helper.rb:345:in `image_tag'
[20a94cbf-f983-4236-9386-52e02c46da86] vendor/bundle/ruby/2.7.0/gems/locomotivecms-4.0.3/app/views/locomotive/content_assets/_list.html.slim:19:in `block in _vendor_bundle_ruby_______gems_locomotivecms_______app_views_locomotive_content_assets__list_html_slim___2110994173039654186_99840'
```

**Comment by numito** [comment]
Engine 4.0.3

**Comment by owaisali01** [comment]
<% if restaurant.try(:image).try(:url)%> try this with your image url @numito
