### ISSUE TITLE
Update to 2.2.3 : Old Content Entries with updated data and new customs fields will not save.

### ISSUE THREAD

**Issue by stunjiturner** [locomotivecms/engine#797]
When i add a new custom field to a content model, only the new content entries created with 2.2.3 will save!, the older entries in the database will not save. the log output when that happens is located here. I am on heroku instance, and ran all migrations.

 Started PUT "/admin/content_types/projects/entries/50396e1e17facd0002000245" for 108.52.5.23 at 2013-09-09 16:44:31 +0000
2013-09-09T16:44:31.795836+00:00 app[web.1]: [LocomotiveCMS] [fetch site] host = beta.sightuary.com / beta.sightuary.com
2013-09-09T16:44:31.835473+00:00 app[web.1]: 
2013-09-09T16:44:31.835473+00:00 app[web.1]: NoMethodError (undefined method `merge!' for "buildingbloqs":String):
2013-09-09T16:44:31.835473+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/attributes.rb:188:in `block in write_attribute'
2013-09-09T16:44:31.835473+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/threaded/lifecycle.rb:26:in `_assigning'
2013-09-09T16:44:31.835473+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/attributes.rb:180:in `write_attribute'
2013-09-09T16:44:31.835473+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/fields.rb:437:in `block (2 levels) in create_field_setter'
2013-09-09T16:44:31.835473+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/attributes/processing.rb:127:in `process_attribute'
2013-09-09T16:44:31.835473+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/attributes/processing.rb:28:in `block (2 levels) in process_attributes'
2013-09-09T16:44:31.835473+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/attributes/processing.rb:26:in `each_pair'
2013-09-09T16:44:31.835473+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/attributes/processing.rb:26:in `block in process_attributes'
2013-09-09T16:44:31.835703+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/attributes/processing.rb:193:in `with_mass_assignment'
2013-09-09T16:44:31.835703+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/attributes/processing.rb:22:in `process_attributes'
2013-09-09T16:44:31.835703+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/attributes.rb:215:in `block in assign_attributes'
2013-09-09T16:44:31.835703+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/threaded/lifecycle.rb:26:in `_assigning'
2013-09-09T16:44:31.835703+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/attributes.rb:214:in `assign_attributes'
2013-09-09T16:44:31.835703+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/persistence.rb:181:in `update_attributes'
2013-09-09T16:44:31.835703+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/locomotive_cms-2.2.3/app/controllers/locomotive/content_entries_controller.rb:62:in `update'
2013-09-09T16:44:31.835703+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
2013-09-09T16:44:31.835703+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/abstract_controller/base.rb:167:in `process_action'
2013-09-09T16:44:31.835703+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal/rendering.rb:10:in `process_action'
2013-09-09T16:44:31.835857+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
2013-09-09T16:44:31.835857+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:568:in `_run__4230086882844153777__process_action__4016309956594193698__callbacks'
2013-09-09T16:44:31.835857+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `__run_callback'
2013-09-09T16:44:31.835857+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
2013-09-09T16:44:31.835857+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in `run_callbacks'
2013-09-09T16:44:31.835857+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/abstract_controller/callbacks.rb:17:in `process_action'
2013-09-09T16:44:31.835857+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal/rescue.rb:29:in `process_action'
2013-09-09T16:44:31.835857+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
2013-09-09T16:44:31.835857+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in `block in instrument'
2013-09-09T16:44:31.835857+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2013-09-09T16:44:31.836303+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in `instrument'
2013-09-09T16:44:31.836303+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
2013-09-09T16:44:31.836303+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
2013-09-09T16:44:31.836303+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/abstract_controller/base.rb:121:in `process'
2013-09-09T16:44:31.836303+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/abstract_controller/rendering.rb:45:in `process'
2013-09-09T16:44:31.836303+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal.rb:203:in `dispatch'
2013-09-09T16:44:31.836303+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
2013-09-09T16:44:31.836303+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_controller/metal.rb:246:in `block in action'
2013-09-09T16:44:31.836303+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:73:in `call'
2013-09-09T16:44:31.836303+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
2013-09-09T16:44:31.836455+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:36:in `call'
2013-09-09T16:44:31.836455+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
2013-09-09T16:44:31.836455+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
2013-09-09T16:44:31.836455+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
2013-09-09T16:44:31.836455+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:612:in `call'
2013-09-09T16:44:31.836455+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/engine.rb:479:in `call'
2013-09-09T16:44:31.836455+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
2013-09-09T16:44:31.836455+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
2013-09-09T16:44:31.836455+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
2013-09-09T16:44:31.836455+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
2013-09-09T16:44:31.836786+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:612:in `call'
2013-09-09T16:44:31.836786+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/locomotive_cms-2.2.3/lib/locomotive/middlewares/inline_editor.rb:10:in `call'
2013-09-09T16:44:31.836786+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/locomotive_cms-2.2.3/lib/locomotive/middlewares/seo_trailing_slash.rb:16:in `call'
2013-09-09T16:44:31.836786+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/rack/mongoid/middleware/identity_map.rb:34:in `block in call'
2013-09-09T16:44:31.836786+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/unit_of_work.rb:39:in `unit_of_work'
2013-09-09T16:44:31.836786+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/rack/mongoid/middleware/identity_map.rb:34:in `call'
2013-09-09T16:44:31.836786+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
2013-09-09T16:44:31.836786+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
2013-09-09T16:44:31.836786+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
2013-09-09T16:44:31.836786+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
2013-09-09T16:44:31.836936+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
2013-09-09T16:44:31.836936+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'
2013-09-09T16:44:31.836936+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/head.rb:14:in `call'
2013-09-09T16:44:31.836936+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
2013-09-09T16:44:31.836936+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/flash.rb:242:in `call'
2013-09-09T16:44:31.836936+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
2013-09-09T16:44:31.836936+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
2013-09-09T16:44:31.836936+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/cookies.rb:341:in `call'
2013-09-09T16:44:31.836936+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/dragonfly-0.9.15/lib/dragonfly/cookie_monster.rb:9:in `call'
2013-09-09T16:44:31.836936+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
2013-09-09T16:44:31.837246+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `_run__3457366310081428782__call__3913252281048569507__callbacks'
2013-09-09T16:44:31.837246+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `__run_callback'
2013-09-09T16:44:31.837246+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
2013-09-09T16:44:31.837246+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in `run_callbacks'
2013-09-09T16:44:31.837246+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2013-09-09T16:44:31.837246+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
2013-09-09T16:44:31.837246+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
2013-09-09T16:44:31.837246+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
2013-09-09T16:44:31.837246+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/rack/logger.rb:32:in `call_app'
2013-09-09T16:44:31.837246+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/rack/logger.rb:16:in `block in call'
2013-09-09T16:44:31.837418+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/tagged_logging.rb:22:in `tagged'
2013-09-09T16:44:31.837418+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/rack/logger.rb:16:in `call'
2013-09-09T16:44:31.837418+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/request_id.rb:22:in `call'
2013-09-09T16:44:31.837418+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
2013-09-09T16:44:31.837418+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
2013-09-09T16:44:31.837418+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
2013-09-09T16:44:31.837418+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
2013-09-09T16:44:31.837418+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/static.rb:63:in `call'
2013-09-09T16:44:31.837418+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
2013-09-09T16:44:31.837418+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in `pass'
2013-09-09T16:44:31.837748+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:155:in `invalidate'
2013-09-09T16:44:31.837748+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:71:in `call!'
2013-09-09T16:44:31.837748+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
2013-09-09T16:44:31.837748+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/dragonfly-0.9.15/lib/dragonfly/middleware.rb:13:in `call'
2013-09-09T16:44:31.837748+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/locomotive_cms-2.2.3/lib/locomotive/middlewares/cache.rb:20:in `call'
2013-09-09T16:44:31.837748+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/locomotive_cms-2.2.3/lib/locomotive/middlewares/permalink.rb:17:in `call'
2013-09-09T16:44:31.837748+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/engine.rb:479:in `call'
2013-09-09T16:44:31.837748+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/application.rb:223:in `call'
2013-09-09T16:44:31.837748+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
2013-09-09T16:44:31.837748+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
2013-09-09T16:44:31.837899+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
2013-09-09T16:44:31.837899+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
2013-09-09T16:44:31.837899+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
2013-09-09T16:44:31.837899+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
2013-09-09T16:44:31.837899+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
2013-09-09T16:44:31.837899+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
2013-09-09T16:44:31.837899+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/thin-1.5.1/lib/thin/backends/base.rb:63:in `start'
2013-09-09T16:44:31.837899+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/thin-1.5.1/lib/thin/server.rb:159:in `start'
2013-09-09T16:44:31.837899+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/thin-1.5.1/lib/thin/controllers/controller.rb:86:in `start'
2013-09-09T16:44:31.837899+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/thin-1.5.1/lib/thin/runner.rb:187:in `run_command'
2013-09-09T16:44:31.838208+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/thin-1.5.1/lib/thin/runner.rb:152:in `run!'
2013-09-09T16:44:31.838208+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/thin-1.5.1/bin/thin:6:in `<top (required)>'
2013-09-09T16:44:31.838208+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/bin/thin:23:in `load'
2013-09-09T16:44:31.838208+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/bin/thin:23:in `<main>'
2013-09-09T16:44:31.838208+00:00 app[web.1]: 
2013-09-09T16:44:31.838208+00:00 app[web.1]:

**Comment by did** [comment]
closing it since v3 is out.
