### ISSUE TITLE
Cannot push liquid page or save template edits on Heroku

### ISSUE THREAD

**Issue by aeberlin** [locomotivecms/engine#942]
I cannot push pages to my production environment on Heroku.

And I don't have anything very complex in my .liquid files (see bottom).

```
$ bundle exec wagon push production -r pages
* Pushing Site
* Pushing Pages
  en
    updating index      error => undefined method `context' for #<Liquid::Document:0x007fe22c76a820>
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter/writer/api/base.rb:131:in `put'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter/writer/api/pages_writer.rb:111:in `update_page'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter/writer/api/pages_writer.rb:63:in `write_page'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter/writer/api/pages_writer.rb:47:in `block (2 levels) in write'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter/writer/api/pages_writer.rb:47:in `each'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter/writer/api/pages_writer.rb:47:in `block in write'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter/writer/api/base.rb:149:in `call'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter/writer/api/base.rb:149:in `block (2 levels) in each_locale'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter.rb:95:in `with_locale'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter/writer/api/base.rb:148:in `block in each_locale'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter/writer/api/base.rb:147:in `each'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter/writer/api/base.rb:147:in `each_locale'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter/writer/api/pages_writer.rb:43:in `write'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter/writer/runner.rb:55:in `block in write_all'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter/writer/runner.rb:51:in `each'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter/writer/runner.rb:51:in `write_all'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_mounter-1.4.0/lib/locomotive/mounter/writer/runner.rb:29:in `run!'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_wagon-1.4.0/lib/locomotive/wagon.rb:82:in `push'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_wagon-1.4.0/lib/locomotive/wagon/cli.rb:196:in `push'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@locomotive/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@locomotive/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@locomotive/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@locomotive/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/gems/locomotivecms_wagon-1.4.0/bin/wagon:9:in `<top (required)>'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/bin/wagon:23:in `load'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@global/bin/wagon:23:in `<main>'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@locomotive/bin/ruby_executable_hooks:15:in `eval'
	/Users/aeberlin/.rvm/gems/ruby-2.1.2@locomotive/bin/ruby_executable_hooks:15:in `<main>'
```

index.liquid:
```
---
title: Home
published: true
---
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    {{ 'application.css' | stylesheet_tag }}
  </head>
  <body>
    <img src="/assets/logo.png" style="height: 136px; width: 396px;" />
  </body>
</html>
```

404.liquid:
```
---
title: Page not found
published: false
---
{% extends index %}

{% block 'main' %}

<p>Page not found</p>

{% endblock %}
```

contact.liquid:
```
<html>
  <body>
    <form method="POST" action="{{contents.contact_messages.public_submission_url}}">
      {% csrf_param %}
      <input type="hidden" value="/" name="success_callback" />
      <input type="hidden" value="/contact" name="error_callback" />

      {% if contact_message.errors %}
        <p>The following errors occured:</p>
        <ul>
        {% for error in contact_message.errors %}
          <li>{{error[0] | capitalize}} -  {{error[1]}}</li>
        {% endfor %}
        </ul>
      {% endif %}

      <table>
        <tr>
          <td>Name:</td>
          <td><input type="text" name="content[name]" value="{{contact_message.name}}"></td>
        </tr>
        <tr>
          <td>Email:</td>
          <td><input type="text" name="content[email]" value="{{contact_message.email}}"></td>
        </tr>
        <tr>
          <td>Message:</td>
          <td><textarea name="content[message]">{{contact_message.message}}</textarea></td>
        </tr>
      </table>
      <input type="submit">
    </form>
  </body>
</html>
```
Additionally, I am not able to save page edits from Heroku. It only says "Your form is being submitted," which quickly disappears and nothing else happens. Here is the error recorded from the javascript console:

```
Failed to load resource: 
The server responded with a status of 500 (Internal Server Error)
http://somewhere.com/locomotive/pages/53974610e98c3747eb000004

Uncaught SyntaxError: Unexpected token <
http://somewhere.com/locomotive/pages/53974610e98c3747eb000004/edit:1
```

The engine has not been modified, only minor changes to config, application.css, and liquid pages.

Hopefully somebody has a solution.. Thanks.. Cheers.

**Comment by did** [comment]
Works fine in V3.
